from .calorimetry_record import CalorimetryRecord
from .compositional_record import CompositionalRecord
from .ftnir_record import FtnirRecord
from .icp_record import IcpRecord
from .proximate_record import ProximateRecord
from .rgb_record import RgbRecord
from .ultimate_record import UltimateRecord
from .xrd_record import XrdRecord
from .xrf_record import XrfRecord
