id: https://w3id.org/ca_biositing/infrastructure/infrastructure_biosolids_facilities
name: infrastructure_biosolids_facilities
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
  - ../core/base_entity
default_range: string

classes:
  InfrastructureBiosolidsFacilities:
    description: Biosolids facilities infrastructure.
    slots:
      - biosolid_facility_id
      - report_submitted_date
      - latitude
      - longitude
      - facility
      - authority
      - plant_type
      - aqmd
      - facility_address
      - facility_city
      - state
      - facility_zip
      - facility_county
      - mailing_street_1
      - mailing_city
      - mailing_state
      - mailing_zip
      - biosolids_number
      - biosolids_contact
      - biosolids_contact_phone
      - biosolids_contact_email
      - adwf
      - potw_biosolids_generated
      - twtds_biosolids_treated
      - class_b_land_app
      - class_b_applier
      - class_a_compost
      - class_a_heat_dried
      - class_a_other
      - class_a_other_applier
      - twtds_transfer_to_second_preparer
      - twtds_second_preparer_name
      - adc_or_final_c
      - landfill
      - landfill_name
      - surface_disposal
      - deepwell_injection
      - stored
      - longterm_treatment
      - other
      - name_of_other
      - incineration
    slot_usage:
      biosolid_facility_id:
        identifier: true
        range: integer

slots:
  biosolid_facility_id:
    range: integer
    description: ID of the biosolids facility.

  report_submitted_date:
    range: date
    description: Date report submitted.

  latitude:
    range: decimal
    description: Latitude.

  longitude:
    range: decimal
    description: Longitude.

  facility:
    range: string
    description: Facility name.

  authority:
    range: string
    description: Authority.

  plant_type:
    range: string
    description: Plant type.

  aqmd:
    range: string
    description: AQMD.

  facility_address:
    range: string
    description: Facility address.

  facility_city:
    range: string
    description: Facility city.

  state:
    range: string
    description: State.

  facility_zip:
    range: string
    description: Facility zip.

  facility_county:
    range: string
    description: Facility county.

  mailing_street_1:
    range: string
    description: Mailing street 1.

  mailing_city:
    range: string
    description: Mailing city.

  mailing_state:
    range: string
    description: Mailing state.

  mailing_zip:
    range: string
    description: Mailing zip.

  biosolids_number:
    range: string
    description: Biosolids number.

  biosolids_contact:
    range: string
    description: Biosolids contact.

  biosolids_contact_phone:
    range: string
    description: Biosolids contact phone.

  biosolids_contact_email:
    range: string
    description: Biosolids contact email.

  adwf:
    range: decimal
    description: ADWF.

  potw_biosolids_generated:
    range: integer
    description: POTW biosolids generated.

  twtds_biosolids_treated:
    range: integer
    description: TWTDS biosolids treated.

  class_b_land_app:
    range: integer
    description: Class B land application.

  class_b_applier:
    range: string
    description: Class B applier.

  class_a_compost:
    range: integer
    description: Class A compost.

  class_a_heat_dried:
    range: integer
    description: Class A heat dried.

  class_a_other:
    range: integer
    description: Class A other.

  class_a_other_applier:
    range: string
    description: Class A other applier.

  twtds_transfer_to_second_preparer:
    range: integer
    description: TWTDS transfer to second preparer.

  twtds_second_preparer_name:
    range: string
    description: TWTDS second preparer name.

  adc_or_final_c:
    range: integer
    description: ADC or final cover.

  landfill:
    range: integer
    description: Landfill.

  landfill_name:
    range: string
    description: Landfill name.

  surface_disposal:
    range: integer
    description: Surface disposal.

  deepwell_injection:
    range: string
    description: Deepwell injection.

  stored:
    range: integer
    description: Stored.

  longterm_treatment:
    range: integer
    description: Longterm treatment.

  other:
    range: integer
    description: Other.

  name_of_other:
    range: string
    description: Name of other.

  incineration:
    range: integer
    description: Incineration.
