"""Consolidated volume estimation and biomass search views

Revision ID: consolidated_views_volume
Revises: consolidated_base_residue
Create Date: 2026-04-24 15:13:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'consolidated_views_volume'
down_revision = 'consolidated_base_residue'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create mv_volume_estimation and update mv_biomass_search."""

    # 1. Create mv_volume_estimation
    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_volume_estimation CASCADE")
    op.execute("""
        CREATE MATERIALIZED VIEW data_portal.mv_volume_estimation AS
        SELECT row_number() OVER (ORDER BY anon_1.resource_id, anon_1.geoid, anon_1.dataset_year, anon_1.volume_source) AS id, anon_1.resource_id, anon_1.resource_name, anon_1.geoid, anon_1.county, anon_1.state, anon_1.dataset_year, anon_1.primary_product_volume AS production_volume, anon_1.volume_unit AS production_unit, anon_1.factor_min, anon_1.factor_mid, anon_1.factor_max, anon_1.estimated_residue_volume_min, anon_1.estimated_residue_volume_mid, anon_1.estimated_residue_volume_max, anon_1.volume_source, anon_1.biomass_unit
        FROM (SELECT resource.id AS resource_id, resource.name AS resource_name, county_ag_report_record.geoid AS geoid, place.county_name AS county, place.state_name AS state, county_ag_report_record.data_year AS dataset_year, county_ag_report_record.record_id AS record_id, avg(observation.value) AS primary_product_volume, max(unit.name) AS volume_unit, residue_factor.factor_min AS factor_min, residue_factor.factor_mid AS factor_mid, residue_factor.factor_max AS factor_max, avg(observation.value) * residue_factor.factor_min AS estimated_residue_volume_min, avg(observation.value) * residue_factor.factor_mid AS estimated_residue_volume_mid, avg(observation.value) * residue_factor.factor_max AS estimated_residue_volume_max, 'production_based' AS volume_source, 'dry_tons' AS biomass_unit
        FROM county_ag_report_record
        JOIN resource ON county_ag_report_record.primary_ag_product_id = resource.primary_ag_product_id
        JOIN residue_factor ON residue_factor.resource_id = resource.id
        JOIN place ON county_ag_report_record.geoid = place.geoid
        LEFT OUTER JOIN observation ON observation.record_id = county_ag_report_record.record_id AND observation.record_type = 'county_ag_report_record'
        LEFT OUTER JOIN unit ON observation.unit_id = unit.id
        WHERE residue_factor.factor_type = 'weight' AND county_ag_report_record.data_year >= 2017 GROUP BY resource.id, resource.name, county_ag_report_record.geoid, place.county_name, place.state_name, county_ag_report_record.data_year, county_ag_report_record.record_id, residue_factor.factor_min, residue_factor.factor_mid, residue_factor.factor_max) AS anon_1 UNION ALL SELECT row_number() OVER (ORDER BY anon_2.resource_id, anon_2.geoid, anon_2.dataset_year, anon_2.volume_source) AS id, anon_2.resource_id, anon_2.resource_name, anon_2.geoid, anon_2.county, anon_2.state, anon_2.dataset_year, anon_2.bearing_acres AS production_volume, anon_2.volume_unit AS production_unit, NULL AS factor_min, NULL AS factor_mid, NULL AS factor_max, anon_2.estimated_residue_volume_min, anon_2.estimated_residue_volume_mid, anon_2.estimated_residue_volume_max, anon_2.volume_source, anon_2.biomass_unit
        FROM (SELECT resource.id AS resource_id, resource.name AS resource_name, usda_census_record.geoid AS geoid, place.county_name AS county, place.state_name AS state, usda_census_record.year AS dataset_year, usda_census_record.id AS record_id, avg(observation.value) AS bearing_acres, 'acres' AS volume_unit, residue_factor.prune_trim_yield AS prune_trim_yield, residue_factor.prune_trim_yield_unit_id AS prune_trim_yield_unit_id, max(unit.name) AS yield_unit, avg(observation.value) * residue_factor.prune_trim_yield AS estimated_residue_volume_min, avg(observation.value) * residue_factor.prune_trim_yield AS estimated_residue_volume_mid, avg(observation.value) * residue_factor.prune_trim_yield AS estimated_residue_volume_max, 'census_bearing_acres' AS volume_source, 'dry_tons' AS biomass_unit
        FROM usda_census_record
        JOIN usda_commodity ON usda_census_record.commodity_code = usda_commodity.id
        JOIN resource_usda_commodity_map ON resource_usda_commodity_map.usda_commodity_id = usda_commodity.id
        JOIN resource ON resource.id = resource_usda_commodity_map.resource_id
        JOIN residue_factor ON residue_factor.resource_id = resource.id
        JOIN place ON usda_census_record.geoid = place.geoid
        LEFT OUTER JOIN observation ON observation.record_id = CAST(usda_census_record.id AS VARCHAR) AND observation.record_type = 'usda_census_record'
        LEFT OUTER JOIN unit ON residue_factor.prune_trim_yield_unit_id = unit.id
        WHERE residue_factor.prune_trim_yield IS NOT NULL AND usda_census_record.year >= 2017 GROUP BY resource.id, resource.name, usda_census_record.geoid, place.county_name, place.state_name, usda_census_record.year, usda_census_record.id, residue_factor.prune_trim_yield, residue_factor.prune_trim_yield_unit_id) AS anon_2
    """)
    op.execute("CREATE UNIQUE INDEX idx_mv_volume_estimation_id ON data_portal.mv_volume_estimation (id)")
    op.execute("GRANT SELECT ON data_portal.mv_volume_estimation TO biocirv_readonly")

    # 2. Update mv_biomass_search
    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_search CASCADE")
    op.execute("""
        CREATE MATERIALIZED VIEW data_portal.mv_biomass_search AS
        SELECT resource.id, resource.name, resource.resource_code, resource.description, resource_class.name AS resource_class, resource_subclass.name AS resource_subclass, coalesce(primary_ag_product.name, anon_1.primary_product_fallback) AS primary_product, resource_morphology.morphology_uri AS image_url, resource.uri AS literature_uri, anon_2.total_annual_volume, anon_2.county_count, anon_2.volume_unit, anon_3.moisture_percent, anon_3.sugar_content_percent, anon_3.glucan_percent, anon_3.xylan_percent, anon_3.ash_percent, anon_3.lignin_percent, anon_3.carbon_percent, anon_3.hydrogen_percent, anon_3.cn_ratio, anon_4.transport_notes, anon_5.storage_notes, coalesce(anon_6.tags, CAST(ARRAY[] AS VARCHAR[])) AS tags, anon_7.from_month AS season_from_month, anon_7.to_month AS season_to_month, anon_7.year_round, coalesce(anon_3.has_proximate, false) AS has_proximate, coalesce(anon_3.has_compositional, false) AS has_compositional, coalesce(anon_3.has_ultimate, false) AS has_ultimate, coalesce(anon_3.has_xrf, false) AS has_xrf, coalesce(anon_3.has_icp, false) AS has_icp, coalesce(anon_3.has_calorimetry, false) AS has_calorimetry, coalesce(anon_3.has_xrd, false) AS has_xrd, coalesce(anon_3.has_ftnir, false) AS has_ftnir, coalesce(anon_3.has_fermentation, false) AS has_fermentation, coalesce(anon_3.has_gasification, false) AS has_gasification, coalesce(anon_3.has_pretreatment, false) AS has_pretreatment, CASE WHEN (anon_3.moisture_percent IS NOT NULL) THEN true ELSE false END AS has_moisture_data, CASE WHEN (anon_3.sugar_content_percent > 0) THEN true ELSE false END AS has_sugar_data, CASE WHEN (resource_morphology.morphology_uri IS NOT NULL) THEN true ELSE false END AS has_image, CASE WHEN (anon_2.total_annual_volume IS NOT NULL) THEN true ELSE false END AS has_volume_data, anon_8.calculated_estimate_volume_min, anon_8.calculated_estimate_volume_max, anon_8.calculated_estimate_volume_mid, resource.created_at, resource.updated_at, to_tsvector('english', coalesce(resource.name, '') || ' ' || coalesce(resource.description, '') || ' ' || coalesce(resource_class.name, '') || ' ' || coalesce(resource_subclass.name, '') || ' ' || coalesce(coalesce(primary_ag_product.name, anon_1.primary_product_fallback), '')) AS search_vector
FROM resource LEFT OUTER JOIN resource_class ON resource.resource_class_id = resource_class.id LEFT OUTER JOIN resource_subclass ON resource.resource_subclass_id = resource_subclass.id LEFT OUTER JOIN primary_ag_product ON resource.primary_ag_product_id = primary_ag_product.id LEFT OUTER JOIN (SELECT resource_usda_commodity_map.resource_id AS resource_id, max(primary_ag_product.name) AS primary_product_fallback
FROM resource_usda_commodity_map JOIN primary_ag_product ON resource_usda_commodity_map.primary_ag_product_id = primary_ag_product.id
WHERE resource_usda_commodity_map.resource_id IS NOT NULL GROUP BY resource_usda_commodity_map.resource_id) AS anon_1 ON anon_1.resource_id = resource.id LEFT OUTER JOIN resource_morphology ON resource_morphology.resource_id = resource.id LEFT OUTER JOIN (SELECT billion_ton2023_record.resource_id AS resource_id, sum(billion_ton2023_record.production) AS total_annual_volume, count(distinct(billion_ton2023_record.geoid)) AS county_count, max(unit.name) AS volume_unit
FROM billion_ton2023_record JOIN unit ON billion_ton2023_record.production_unit_id = unit.id GROUP BY billion_ton2023_record.resource_id) AS anon_2 ON anon_2.resource_id = resource.id LEFT OUTER JOIN (SELECT anon_9.resource_id AS resource_id, sum(anon_9.estimated_residue_volume_min) AS calculated_estimate_volume_min, sum(anon_9.estimated_residue_volume_max) AS calculated_estimate_volume_max, sum(anon_9.estimated_residue_volume_mid) AS calculated_estimate_volume_mid
FROM (SELECT row_number() OVER (ORDER BY anon_10.resource_id, anon_10.geoid, anon_10.dataset_year, anon_10.volume_source) AS id, anon_10.resource_id AS resource_id, anon_10.resource_name AS resource_name, anon_10.geoid AS geoid, anon_10.county AS county, anon_10.state AS state, anon_10.dataset_year AS dataset_year, anon_10.primary_product_volume AS production_volume, anon_10.volume_unit AS production_unit, anon_10.factor_min AS factor_min, anon_10.factor_mid AS factor_mid, anon_10.factor_max AS factor_max, anon_10.estimated_residue_volume_min AS estimated_residue_volume_min, anon_10.estimated_residue_volume_mid AS estimated_residue_volume_mid, anon_10.estimated_residue_volume_max AS estimated_residue_volume_max, anon_10.volume_source AS volume_source, anon_10.biomass_unit AS biomass_unit
FROM (SELECT resource.id AS resource_id, resource.name AS resource_name, county_ag_report_record.geoid AS geoid, place.county_name AS county, place.state_name AS state, county_ag_report_record.data_year AS dataset_year, county_ag_report_record.record_id AS record_id, avg(observation.value) AS primary_product_volume, max(unit.name) AS volume_unit, residue_factor.factor_min AS factor_min, residue_factor.factor_mid AS factor_mid, residue_factor.factor_max AS factor_max, avg(observation.value) * residue_factor.factor_min AS estimated_residue_volume_min, avg(observation.value) * residue_factor.factor_mid AS estimated_residue_volume_mid, avg(observation.value) * residue_factor.factor_max AS estimated_residue_volume_max, 'production_based' AS volume_source, 'dry_tons' AS biomass_unit
FROM county_ag_report_record JOIN resource ON county_ag_report_record.primary_ag_product_id = resource.primary_ag_product_id JOIN residue_factor ON residue_factor.resource_id = resource.id JOIN place ON county_ag_report_record.geoid = place.geoid LEFT OUTER JOIN observation ON observation.record_id = county_ag_report_record.record_id AND observation.record_type = 'county_ag_report_record' LEFT OUTER JOIN unit ON observation.unit_id = unit.id
WHERE residue_factor.factor_type = 'weight' AND county_ag_report_record.data_year >= 2017 GROUP BY resource.id, resource.name, county_ag_report_record.geoid, place.county_name, place.state_name, county_ag_report_record.data_year, county_ag_report_record.record_id, residue_factor.factor_min, residue_factor.factor_mid, residue_factor.factor_max) AS anon_10 UNION ALL SELECT row_number() OVER (ORDER BY anon_11.resource_id, anon_11.geoid, anon_11.dataset_year, anon_11.volume_source) AS id, anon_11.resource_id AS resource_id, anon_11.resource_name AS resource_name, anon_11.geoid AS geoid, anon_11.county AS county, anon_11.state AS state, anon_11.dataset_year AS dataset_year, anon_11.bearing_acres AS production_volume, anon_11.volume_unit AS production_unit, NULL AS factor_min, NULL AS factor_mid, NULL AS factor_max, anon_11.estimated_residue_volume_min AS estimated_residue_volume_min, anon_11.estimated_residue_volume_mid AS estimated_residue_volume_mid, anon_11.estimated_residue_volume_max AS estimated_residue_volume_max, anon_11.volume_source AS volume_source, anon_11.biomass_unit AS biomass_unit
FROM (SELECT resource.id AS resource_id, resource.name AS resource_name, usda_census_record.geoid AS geoid, place.county_name AS county, place.state_name AS state, usda_census_record.year AS dataset_year, usda_census_record.id AS record_id, avg(observation.value) AS bearing_acres, 'acres' AS volume_unit, residue_factor.prune_trim_yield AS prune_trim_yield, residue_factor.prune_trim_yield_unit_id AS prune_trim_yield_unit_id, max(unit.name) AS yield_unit, avg(observation.value) * residue_factor.prune_trim_yield AS estimated_residue_volume_min, avg(observation.value) * residue_factor.prune_trim_yield AS estimated_residue_volume_mid, avg(observation.value) * residue_factor.prune_trim_yield AS estimated_residue_volume_max, 'census_bearing_acres' AS volume_source, 'dry_tons' AS biomass_unit
FROM usda_census_record JOIN usda_commodity ON usda_census_record.commodity_code = usda_commodity.id JOIN resource_usda_commodity_map ON resource_usda_commodity_map.usda_commodity_id = usda_commodity.id JOIN resource ON resource.id = resource_usda_commodity_map.resource_id JOIN residue_factor ON residue_factor.resource_id = resource.id JOIN place ON usda_census_record.geoid = place.geoid LEFT OUTER JOIN observation ON observation.record_id = CAST(usda_census_record.id AS VARCHAR) AND observation.record_type = 'usda_census_record' LEFT OUTER JOIN unit ON residue_factor.prune_trim_yield_unit_id = unit.id
WHERE residue_factor.prune_trim_yield IS NOT NULL AND usda_census_record.year >= 2017 GROUP BY resource.id, resource.name, usda_census_record.geoid, place.county_name, place.state_name, usda_census_record.year, usda_census_record.id, residue_factor.prune_trim_yield, residue_factor.prune_trim_yield_unit_id) AS anon_11) AS anon_9
WHERE anon_9.dataset_year = 2024 GROUP BY anon_9.resource_id) AS anon_8 ON anon_8.resource_id = resource.id LEFT OUTER JOIN (SELECT anon_12.resource_id AS resource_id, avg(CASE WHEN (anon_13.parameter = 'moisture') THEN anon_13.value END) AS moisture_percent, avg(CASE WHEN (anon_13.parameter = 'ash') THEN anon_13.value END) AS ash_percent, CASE WHEN (avg(CASE WHEN (anon_13.parameter = 'lignin') THEN anon_13.value END) IS NOT NULL OR avg(CASE WHEN (anon_13.parameter = 'lignin+') THEN anon_13.value END) IS NOT NULL) THEN coalesce(avg(CASE WHEN (anon_13.parameter = 'lignin') THEN anon_13.value END), 0) + coalesce(avg(CASE WHEN (anon_13.parameter = 'lignin+') THEN anon_13.value END), 0) END AS lignin_percent, CASE WHEN (avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END) IS NOT NULL OR avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END) IS NOT NULL) THEN coalesce(avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END), 0) + coalesce(avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END), 0) END AS sugar_content_percent, avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END) AS glucan_percent, avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END) AS xylan_percent, avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) AS carbon_percent, avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'hydrogen') THEN anon_13.value END) AS hydrogen_percent, CASE WHEN (avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) IS NOT NULL AND avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) IS NOT NULL AND avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) != 0) THEN avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) / CAST(CAST(avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) AS NUMERIC) AS NUMERIC) END AS cn_ratio, bool_or(anon_12.type = 'proximate analysis') AS has_proximate, bool_or(anon_12.type = 'compositional analysis') AS has_compositional, bool_or(anon_12.type = 'ultimate analysis') AS has_ultimate, bool_or(anon_12.type = 'xrf analysis') AS has_xrf, bool_or(anon_12.type = 'icp analysis') AS has_icp, bool_or(anon_12.type = 'calorimetry analysis') AS has_calorimetry, bool_or(anon_12.type = 'xrd analysis') AS has_xrd, bool_or(anon_12.type = 'ftnir analysis') AS has_ftnir, bool_or(anon_12.type = 'fermentation') AS has_fermentation, bool_or(anon_12.type = 'gasification') AS has_gasification, bool_or(anon_12.type = 'pretreatment') AS has_pretreatment
FROM (SELECT CAST(compositional_record.resource_id AS INTEGER) AS resource_id, CAST(compositional_record.record_id AS VARCHAR) AS record_id, 'compositional analysis' AS type
FROM compositional_record
WHERE compositional_record.qc_pass != 'fail' UNION ALL SELECT CAST(proximate_record.resource_id AS INTEGER) AS resource_id, CAST(proximate_record.record_id AS VARCHAR) AS record_id, 'proximate analysis' AS anon_14
FROM proximate_record
WHERE proximate_record.qc_pass != 'fail' UNION ALL SELECT CAST(ultimate_record.resource_id AS INTEGER) AS resource_id, CAST(ultimate_record.record_id AS VARCHAR) AS record_id, 'ultimate analysis' AS anon_15
FROM ultimate_record
WHERE ultimate_record.qc_pass != 'fail' UNION ALL SELECT CAST(xrf_record.resource_id AS INTEGER) AS resource_id, CAST(xrf_record.record_id AS VARCHAR) AS record_id, 'xrf analysis' AS anon_16
FROM xrf_record
WHERE xrf_record.qc_pass != 'fail' UNION ALL SELECT CAST(icp_record.resource_id AS INTEGER) AS resource_id, CAST(icp_record.record_id AS VARCHAR) AS record_id, 'icp analysis' AS anon_17
FROM icp_record
WHERE icp_record.qc_pass != 'fail' UNION ALL SELECT CAST(calorimetry_record.resource_id AS INTEGER) AS resource_id, CAST(calorimetry_record.record_id AS VARCHAR) AS record_id, 'calorimetry analysis' AS anon_18
FROM calorimetry_record
WHERE calorimetry_record.qc_pass != 'fail' UNION ALL SELECT CAST(xrd_record.resource_id AS INTEGER) AS resource_id, CAST(xrd_record.record_id AS VARCHAR) AS record_id, 'xrd analysis' AS anon_19
FROM xrd_record
WHERE xrd_record.qc_pass != 'fail' UNION ALL SELECT CAST(ftnir_record.resource_id AS INTEGER) AS resource_id, CAST(ftnir_record.record_id AS VARCHAR) AS record_id, 'ftnir analysis' AS anon_20
FROM ftnir_record
WHERE ftnir_record.qc_pass != 'fail' UNION ALL SELECT CAST(fermentation_record.resource_id AS INTEGER) AS resource_id, CAST(fermentation_record.record_id AS VARCHAR) AS record_id, 'fermentation' AS anon_21
FROM fermentation_record
WHERE fermentation_record.qc_pass != 'fail' UNION ALL SELECT CAST(gasification_record.resource_id AS INTEGER) AS resource_id, CAST(gasification_record.record_id AS VARCHAR) AS record_id, 'gasification' AS anon_22
FROM gasification_record
WHERE gasification_record.qc_pass != 'fail' UNION ALL SELECT CAST(pretreatment_record.resource_id AS INTEGER) AS resource_id, CAST(pretreatment_record.record_id AS VARCHAR) AS record_id, 'pretreatment' AS anon_23
FROM pretreatment_record
WHERE pretreatment_record.qc_pass != 'fail') AS anon_12 LEFT OUTER JOIN (SELECT CAST(observation.record_id AS VARCHAR) AS record_id, CAST(observation.record_type AS VARCHAR) AS record_type, parameter.name AS parameter, observation.value AS value
FROM observation JOIN parameter ON observation.parameter_id = parameter.id
WHERE observation.record_type IN ('compositional analysis', 'proximate analysis', 'ultimate analysis', 'xrf analysis', 'icp analysis', 'calorimetry analysis', 'xrd analysis', 'ftnir analysis', 'pretreatment', 'gasification', 'fermentation')) AS anon_13 ON lower(anon_12.record_id) = lower(anon_13.record_id) AND anon_13.record_type = anon_12.type GROUP BY anon_12.resource_id) AS anon_3 ON anon_3.resource_id = resource.id LEFT OUTER JOIN (SELECT anon_3.resource_id AS resource_id, array_remove(ARRAY[CASE WHEN (anon_3.moisture_percent <= anon_24.moisture_low) THEN 'low moisture' END, CASE WHEN (anon_3.moisture_percent >= anon_24.moisture_high) THEN 'high moisture' END, CASE WHEN (anon_3.ash_percent <= anon_24.ash_low) THEN 'low ash' END, CASE WHEN (anon_3.ash_percent >= anon_24.ash_high) THEN 'high ash' END, CASE WHEN (anon_3.lignin_percent <= anon_24.lignin_low) THEN 'low lignin' END, CASE WHEN (anon_3.lignin_percent >= anon_24.lignin_high) THEN 'high lignin' END, CASE WHEN (anon_3.glucan_percent <= anon_24.glucan_low) THEN 'low glucan' END, CASE WHEN (anon_3.glucan_percent >= anon_24.glucan_high) THEN 'high glucan' END, CASE WHEN (anon_3.xylan_percent <= anon_24.xylan_low) THEN 'low xylan' END, CASE WHEN (anon_3.xylan_percent >= anon_24.xylan_high) THEN 'high xylan' END], NULL) AS tags
FROM (SELECT anon_12.resource_id AS resource_id, avg(CASE WHEN (anon_13.parameter = 'moisture') THEN anon_13.value END) AS moisture_percent, avg(CASE WHEN (anon_13.parameter = 'ash') THEN anon_13.value END) AS ash_percent, CASE WHEN (avg(CASE WHEN (anon_13.parameter = 'lignin') THEN anon_13.value END) IS NOT NULL OR avg(CASE WHEN (anon_13.parameter = 'lignin+') THEN anon_13.value END) IS NOT NULL) THEN coalesce(avg(CASE WHEN (anon_13.parameter = 'lignin') THEN anon_13.value END), 0) + coalesce(avg(CASE WHEN (anon_13.parameter = 'lignin+') THEN anon_13.value END), 0) END AS lignin_percent, CASE WHEN (avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END) IS NOT NULL OR avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END) IS NOT NULL) THEN coalesce(avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END), 0) + coalesce(avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END), 0) END AS sugar_content_percent, avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END) AS glucan_percent, avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END) AS xylan_percent, avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) AS carbon_percent, avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'hydrogen') THEN anon_13.value END) AS hydrogen_percent, CASE WHEN (avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) IS NOT NULL AND avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) IS NOT NULL AND avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) != 0) THEN avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) / CAST(CAST(avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) AS NUMERIC) AS NUMERIC) END AS cn_ratio, bool_or(anon_12.type = 'proximate analysis') AS has_proximate, bool_or(anon_12.type = 'compositional analysis') AS has_compositional, bool_or(anon_12.type = 'ultimate analysis') AS has_ultimate, bool_or(anon_12.type = 'xrf analysis') AS has_xrf, bool_or(anon_12.type = 'icp analysis') AS has_icp, bool_or(anon_12.type = 'calorimetry analysis') AS has_calorimetry, bool_or(anon_12.type = 'xrd analysis') AS has_xrd, bool_or(anon_12.type = 'ftnir analysis') AS has_ftnir, bool_or(anon_12.type = 'fermentation') AS has_fermentation, bool_or(anon_12.type = 'gasification') AS has_gasification, bool_or(anon_12.type = 'pretreatment') AS has_pretreatment
FROM (SELECT CAST(compositional_record.resource_id AS INTEGER) AS resource_id, CAST(compositional_record.record_id AS VARCHAR) AS record_id, 'compositional analysis' AS type
FROM compositional_record
WHERE compositional_record.qc_pass != 'fail' UNION ALL SELECT CAST(proximate_record.resource_id AS INTEGER) AS resource_id, CAST(proximate_record.record_id AS VARCHAR) AS record_id, 'proximate analysis' AS anon_14
FROM proximate_record
WHERE proximate_record.qc_pass != 'fail' UNION ALL SELECT CAST(ultimate_record.resource_id AS INTEGER) AS resource_id, CAST(ultimate_record.record_id AS VARCHAR) AS record_id, 'ultimate analysis' AS anon_15
FROM ultimate_record
WHERE ultimate_record.qc_pass != 'fail' UNION ALL SELECT CAST(xrf_record.resource_id AS INTEGER) AS resource_id, CAST(xrf_record.record_id AS VARCHAR) AS record_id, 'xrf analysis' AS anon_16
FROM xrf_record
WHERE xrf_record.qc_pass != 'fail' UNION ALL SELECT CAST(icp_record.resource_id AS INTEGER) AS resource_id, CAST(icp_record.record_id AS VARCHAR) AS record_id, 'icp analysis' AS anon_17
FROM icp_record
WHERE icp_record.qc_pass != 'fail' UNION ALL SELECT CAST(calorimetry_record.resource_id AS INTEGER) AS resource_id, CAST(calorimetry_record.record_id AS VARCHAR) AS record_id, 'calorimetry analysis' AS anon_18
FROM calorimetry_record
WHERE calorimetry_record.qc_pass != 'fail' UNION ALL SELECT CAST(xrd_record.resource_id AS INTEGER) AS resource_id, CAST(xrd_record.record_id AS VARCHAR) AS record_id, 'xrd analysis' AS anon_19
FROM xrd_record
WHERE xrd_record.qc_pass != 'fail' UNION ALL SELECT CAST(ftnir_record.resource_id AS INTEGER) AS resource_id, CAST(ftnir_record.record_id AS VARCHAR) AS record_id, 'ftnir analysis' AS anon_20
FROM ftnir_record
WHERE ftnir_record.qc_pass != 'fail' UNION ALL SELECT CAST(fermentation_record.resource_id AS INTEGER) AS resource_id, CAST(fermentation_record.record_id AS VARCHAR) AS record_id, 'fermentation' AS anon_21
FROM fermentation_record
WHERE fermentation_record.qc_pass != 'fail' UNION ALL SELECT CAST(gasification_record.resource_id AS INTEGER) AS resource_id, CAST(gasification_record.record_id AS VARCHAR) AS record_id, 'gasification' AS anon_22
FROM gasification_record
WHERE gasification_record.qc_pass != 'fail' UNION ALL SELECT CAST(pretreatment_record.resource_id AS INTEGER) AS resource_id, CAST(pretreatment_record.record_id AS VARCHAR) AS record_id, 'pretreatment' AS anon_23
FROM pretreatment_record
WHERE pretreatment_record.qc_pass != 'fail') AS anon_12 LEFT OUTER JOIN (SELECT CAST(observation.record_id AS VARCHAR) AS record_id, CAST(observation.record_type AS VARCHAR) AS record_type, parameter.name AS parameter, observation.value AS value
FROM observation JOIN parameter ON observation.parameter_id = parameter.id
WHERE observation.record_type IN ('compositional analysis', 'proximate analysis', 'ultimate analysis', 'xrf analysis', 'icp analysis', 'calorimetry analysis', 'xrd analysis', 'ftnir analysis', 'pretreatment', 'gasification', 'fermentation')) AS anon_13 ON lower(anon_12.record_id) = lower(anon_13.record_id) AND anon_13.record_type = anon_12.type GROUP BY anon_12.resource_id) AS anon_3 JOIN (SELECT percentile_cont(0.1) WITHIN GROUP (ORDER BY anon_3.moisture_percent) AS moisture_low, percentile_cont(0.9) WITHIN GROUP (ORDER BY anon_3.moisture_percent) AS moisture_high, percentile_cont(0.1) WITHIN GROUP (ORDER BY anon_3.ash_percent) AS ash_low, percentile_cont(0.9) WITHIN GROUP (ORDER BY anon_3.ash_percent) AS ash_high, percentile_cont(0.1) WITHIN GROUP (ORDER BY anon_3.lignin_percent) AS lignin_low, percentile_cont(0.9) WITHIN GROUP (ORDER BY anon_3.lignin_percent) AS lignin_high, percentile_cont(0.1) WITHIN GROUP (ORDER BY anon_3.sugar_content_percent) AS sugar_low, percentile_cont(0.9) WITHIN GROUP (ORDER BY anon_3.sugar_content_percent) AS sugar_high, percentile_cont(0.1) WITHIN GROUP (ORDER BY anon_3.glucan_percent) AS glucan_low, percentile_cont(0.9) WITHIN GROUP (ORDER BY anon_3.glucan_percent) AS glucan_high, percentile_cont(0.1) WITHIN GROUP (ORDER BY anon_3.xylan_percent) AS xylan_low, percentile_cont(0.9) WITHIN GROUP (ORDER BY anon_3.xylan_percent) AS xylan_high
FROM (SELECT anon_12.resource_id AS resource_id, avg(CASE WHEN (anon_13.parameter = 'moisture') THEN anon_13.value END) AS moisture_percent, avg(CASE WHEN (anon_13.parameter = 'ash') THEN anon_13.value END) AS ash_percent, CASE WHEN (avg(CASE WHEN (anon_13.parameter = 'lignin') THEN anon_13.value END) IS NOT NULL OR avg(CASE WHEN (anon_13.parameter = 'lignin+') THEN anon_13.value END) IS NOT NULL) THEN coalesce(avg(CASE WHEN (anon_13.parameter = 'lignin') THEN anon_13.value END), 0) + coalesce(avg(CASE WHEN (anon_13.parameter = 'lignin+') THEN anon_13.value END), 0) END AS lignin_percent, CASE WHEN (avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END) IS NOT NULL OR avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END) IS NOT NULL) THEN coalesce(avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END), 0) + coalesce(avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END), 0) END AS sugar_content_percent, avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END) AS glucan_percent, avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END) AS xylan_percent, avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) AS carbon_percent, avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'hydrogen') THEN anon_13.value END) AS hydrogen_percent, CASE WHEN (avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) IS NOT NULL AND avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) IS NOT NULL AND avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) != 0) THEN avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) / CAST(CAST(avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) AS NUMERIC) AS NUMERIC) END AS cn_ratio, bool_or(anon_12.type = 'proximate analysis') AS has_proximate, bool_or(anon_12.type = 'compositional analysis') AS has_compositional, bool_or(anon_12.type = 'ultimate analysis') AS has_ultimate, bool_or(anon_12.type = 'xrf analysis') AS has_xrf, bool_or(anon_12.type = 'icp analysis') AS has_icp, bool_or(anon_12.type = 'calorimetry analysis') AS has_calorimetry, bool_or(anon_12.type = 'xrd analysis') AS has_xrd, bool_or(anon_12.type = 'ftnir analysis') AS has_ftnir, bool_or(anon_12.type = 'fermentation') AS has_fermentation, bool_or(anon_12.type = 'gasification') AS has_gasification, bool_or(anon_12.type = 'pretreatment') AS has_pretreatment
FROM (SELECT CAST(compositional_record.resource_id AS INTEGER) AS resource_id, CAST(compositional_record.record_id AS VARCHAR) AS record_id, 'compositional analysis' AS type
FROM compositional_record
WHERE compositional_record.qc_pass != 'fail' UNION ALL SELECT CAST(proximate_record.resource_id AS INTEGER) AS resource_id, CAST(proximate_record.record_id AS VARCHAR) AS record_id, 'proximate analysis' AS anon_14
FROM proximate_record
WHERE proximate_record.qc_pass != 'fail' UNION ALL SELECT CAST(ultimate_record.resource_id AS INTEGER) AS resource_id, CAST(ultimate_record.record_id AS VARCHAR) AS record_id, 'ultimate analysis' AS anon_15
FROM ultimate_record
WHERE ultimate_record.qc_pass != 'fail' UNION ALL SELECT CAST(xrf_record.resource_id AS INTEGER) AS resource_id, CAST(xrf_record.record_id AS VARCHAR) AS record_id, 'xrf analysis' AS anon_16
FROM xrf_record
WHERE xrf_record.qc_pass != 'fail' UNION ALL SELECT CAST(icp_record.resource_id AS INTEGER) AS resource_id, CAST(icp_record.record_id AS VARCHAR) AS record_id, 'icp analysis' AS anon_17
FROM icp_record
WHERE icp_record.qc_pass != 'fail' UNION ALL SELECT CAST(calorimetry_record.resource_id AS INTEGER) AS resource_id, CAST(calorimetry_record.record_id AS VARCHAR) AS record_id, 'calorimetry analysis' AS anon_18
FROM calorimetry_record
WHERE calorimetry_record.qc_pass != 'fail' UNION ALL SELECT CAST(xrd_record.resource_id AS INTEGER) AS resource_id, CAST(xrd_record.record_id AS VARCHAR) AS record_id, 'xrd analysis' AS anon_19
FROM xrd_record
WHERE xrd_record.qc_pass != 'fail' UNION ALL SELECT CAST(ftnir_record.resource_id AS INTEGER) AS resource_id, CAST(ftnir_record.record_id AS VARCHAR) AS record_id, 'ftnir analysis' AS anon_20
FROM ftnir_record
WHERE ftnir_record.qc_pass != 'fail' UNION ALL SELECT CAST(fermentation_record.resource_id AS INTEGER) AS resource_id, CAST(fermentation_record.record_id AS VARCHAR) AS record_id, 'fermentation' AS anon_21
FROM fermentation_record
WHERE fermentation_record.qc_pass != 'fail' UNION ALL SELECT CAST(gasification_record.resource_id AS INTEGER) AS resource_id, CAST(gasification_record.record_id AS VARCHAR) AS record_id, 'gasification' AS anon_22
FROM gasification_record
WHERE gasification_record.qc_pass != 'fail' UNION ALL SELECT CAST(pretreatment_record.resource_id AS INTEGER) AS resource_id, CAST(pretreatment_record.record_id AS VARCHAR) AS record_id, 'pretreatment' AS anon_23
FROM pretreatment_record
WHERE pretreatment_record.qc_pass != 'fail') AS anon_12 LEFT OUTER JOIN (SELECT CAST(observation.record_id AS VARCHAR) AS record_id, CAST(observation.record_type AS VARCHAR) AS record_type, parameter.name AS parameter, observation.value AS value
FROM observation JOIN parameter ON observation.parameter_id = parameter.id
WHERE observation.record_type IN ('compositional analysis', 'proximate analysis', 'ultimate analysis', 'xrf analysis', 'icp analysis', 'calorimetry analysis', 'xrd analysis', 'ftnir analysis', 'pretreatment', 'gasification', 'fermentation')) AS anon_13 ON lower(anon_12.record_id) = lower(anon_13.record_id) AND anon_13.record_type = anon_12.type GROUP BY anon_12.resource_id) AS anon_3) AS anon_24 ON true) AS anon_6 ON anon_6.resource_id = resource.id LEFT OUTER JOIN (SELECT resource.id AS resource_id, resource.name AS resource_name, min(resource_availability.from_month) AS from_month, max(resource_availability.to_month) AS to_month, bool_or(resource_availability.year_round) AS year_round, avg(resource_availability.residue_factor_dry_tons_acre) AS dry_tons_per_acre, avg(resource_availability.residue_factor_wet_tons_acre) AS wet_tons_per_acre
FROM resource_availability JOIN resource ON resource_availability.resource_id = resource.id GROUP BY resource.id, resource.name) AS anon_7 ON anon_7.resource_id = resource.id LEFT OUTER JOIN (SELECT resource_transport_record.resource_id AS resource_id, max(resource_transport_record.transport_description) AS transport_notes
FROM resource_transport_record GROUP BY resource_transport_record.resource_id) AS anon_4 ON anon_4.resource_id = resource.id LEFT OUTER JOIN (SELECT resource_storage_record.resource_id AS resource_id, max(resource_storage_record.storage_description) AS storage_notes
FROM resource_storage_record GROUP BY resource_storage_record.resource_id) AS anon_5 ON anon_5.resource_id = resource.id
WHERE lower(resource.name) != 'sargassum' AND lower(resource.name) != 'lab media'
    """)
    op.execute("CREATE UNIQUE INDEX idx_mv_biomass_search_id ON data_portal.mv_biomass_search (id)")
    op.execute("GRANT SELECT ON data_portal.mv_biomass_search TO biocirv_readonly")


def downgrade() -> None:
    """Drop the views."""
    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_search CASCADE")
    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_volume_estimation CASCADE")
