"""testing alembic updating biomass table again

Revision ID: 01bc83d57d67
Revises: cf62fb7813f6
Create Date: 2025-10-24 19:47:56.663870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01bc83d57d67'
down_revision: Union[str, Sequence[str], None] = 'cf62fb7813f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
