"""testing alembic updating biomass test

Revision ID: 09daa1ad6e0b
Revises: 01bc83d57d67
Create Date: 2025-10-24 19:50:25.393413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09daa1ad6e0b'
down_revision: Union[str, Sequence[str], None] = '01bc83d57d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
