"""remove volumes from fermentation_record

Revision ID: 17fab0e1d312
Revises: 7a1a07ff85b0
Create Date: 2026-02-20 09:09:11.979944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17fab0e1d312'
down_revision: Union[str, Sequence[str], None] = '7a1a07ff85b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fermentation_record', 'temperature')
    op.drop_column('fermentation_record', 'reaction_volume_L')
    op.drop_column('fermentation_record', 'inoculum_volume_L')
    op.drop_column('fermentation_record', 'agitation_rpm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fermentation_record', sa.Column('agitation_rpm', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('fermentation_record', sa.Column('inoculum_volume_L', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('fermentation_record', sa.Column('reaction_volume_L', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('fermentation_record', sa.Column('temperature', sa.NUMERIC(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
