"""add use_case lookup table and resoure_end_use_record use_case_id

Revision ID: 1bed1a9104a7
Revises: bd227e99e006
Create Date: 2026-04-14 18:48:51.401528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1bed1a9104a7'
down_revision: Union[str, Sequence[str], None] = 'bd227e99e006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('use_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('resource_end_use_record', sa.Column('use_case_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resource_end_use_record', 'use_case', ['use_case_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resource_end_use_record', type_='foreignkey')
    op.drop_column('resource_end_use_record', 'use_case_id')
    op.drop_table('use_case')
    # ### end Alembic commands ###
