"""changing data types for etl_run and making foreign key connection

Revision ID: 20d0b6aa3316
Revises: 1156a16b5a9c
Create Date: 2026-01-20 12:14:36.722408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d0b6aa3316'
down_revision: Union[str, Sequence[str], None] = '1156a16b5a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aim1_record_base', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'aim1_record_base', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('aim2_record_base', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'aim2_record_base', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('autoclave_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'autoclave_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('base_entity', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'base_entity', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('billion_ton2023_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'billion_ton2023_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('calorimetry_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'calorimetry_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('compositional_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'compositional_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('contact', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'contact', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('data_source', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'data_source', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('data_source_type', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'data_source_type', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('dataset', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'dataset', 'etl_run', ['etl_run_id'], ['id'])
    op.add_column('etl_run', sa.Column('run_id', sa.Text(), nullable=True))
    op.alter_column('experiment', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'experiment', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('facility_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'facility_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('fermentation_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'fermentation_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('field_sample', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'field_sample', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('field_sample_condition', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'field_sample_condition', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('file_object_metadata', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'file_object_metadata', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('ftnir_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'ftnir_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('gasification_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'gasification_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('icp_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'icp_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('landiq_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'landiq_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('lineage_group', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'lineage_group', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('location_address', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'location_address', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('location_soil_type', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'location_soil_type', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('method', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'method', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('observation', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'observation', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('parameter', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'parameter', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('physical_characteristic', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'physical_characteristic', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('preparation_method', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'preparation_method', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('prepared_sample', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'prepared_sample', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('pretreatment_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'pretreatment_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('provider', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'provider', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('proximate_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'proximate_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('resource', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'resource', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('resource_availability', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'resource_availability', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('resource_usda_commodity_map', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'resource_usda_commodity_map', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('rgb_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'rgb_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('ultimate_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'ultimate_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('usda_census_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'usda_census_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('usda_market_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'usda_market_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('usda_market_report', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'usda_market_report', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('usda_survey_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'usda_survey_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('usda_term_map', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'usda_term_map', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('xrd_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'xrd_record', 'etl_run', ['etl_run_id'], ['id'])
    op.alter_column('xrf_record', 'etl_run_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(), postgresql_using="etl_run_id::integer",
               existing_nullable=True)
    op.create_foreign_key(None, 'xrf_record', 'etl_run', ['etl_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'xrf_record', type_='foreignkey')
    op.alter_column('xrf_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'xrd_record', type_='foreignkey')
    op.alter_column('xrd_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'usda_term_map', type_='foreignkey')
    op.alter_column('usda_term_map', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'usda_survey_record', type_='foreignkey')
    op.alter_column('usda_survey_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'usda_market_report', type_='foreignkey')
    op.alter_column('usda_market_report', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'usda_market_record', type_='foreignkey')
    op.alter_column('usda_market_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'usda_census_record', type_='foreignkey')
    op.alter_column('usda_census_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'ultimate_record', type_='foreignkey')
    op.alter_column('ultimate_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'rgb_record', type_='foreignkey')
    op.alter_column('rgb_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'resource_usda_commodity_map', type_='foreignkey')
    op.alter_column('resource_usda_commodity_map', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'resource_availability', type_='foreignkey')
    op.alter_column('resource_availability', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.alter_column('resource', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'proximate_record', type_='foreignkey')
    op.alter_column('proximate_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'provider', type_='foreignkey')
    op.alter_column('provider', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'pretreatment_record', type_='foreignkey')
    op.alter_column('pretreatment_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'prepared_sample', type_='foreignkey')
    op.alter_column('prepared_sample', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'preparation_method', type_='foreignkey')
    op.alter_column('preparation_method', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'physical_characteristic', type_='foreignkey')
    op.alter_column('physical_characteristic', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'parameter', type_='foreignkey')
    op.alter_column('parameter', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'observation', type_='foreignkey')
    op.alter_column('observation', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'method', type_='foreignkey')
    op.alter_column('method', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'location_soil_type', type_='foreignkey')
    op.alter_column('location_soil_type', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'location_address', type_='foreignkey')
    op.alter_column('location_address', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'lineage_group', type_='foreignkey')
    op.alter_column('lineage_group', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'landiq_record', type_='foreignkey')
    op.alter_column('landiq_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'icp_record', type_='foreignkey')
    op.alter_column('icp_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'gasification_record', type_='foreignkey')
    op.alter_column('gasification_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'ftnir_record', type_='foreignkey')
    op.alter_column('ftnir_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'file_object_metadata', type_='foreignkey')
    op.alter_column('file_object_metadata', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'field_sample_condition', type_='foreignkey')
    op.alter_column('field_sample_condition', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'field_sample', type_='foreignkey')
    op.alter_column('field_sample', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'fermentation_record', type_='foreignkey')
    op.alter_column('fermentation_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'facility_record', type_='foreignkey')
    op.alter_column('facility_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.alter_column('experiment', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('etl_run', 'run_id')
    op.drop_constraint(None, 'dataset', type_='foreignkey')
    op.alter_column('dataset', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'data_source_type', type_='foreignkey')
    op.alter_column('data_source_type', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'data_source', type_='foreignkey')
    op.alter_column('data_source', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.alter_column('contact', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'compositional_record', type_='foreignkey')
    op.alter_column('compositional_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'calorimetry_record', type_='foreignkey')
    op.alter_column('calorimetry_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'billion_ton2023_record', type_='foreignkey')
    op.alter_column('billion_ton2023_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'base_entity', type_='foreignkey')
    op.alter_column('base_entity', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'autoclave_record', type_='foreignkey')
    op.alter_column('autoclave_record', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'aim2_record_base', type_='foreignkey')
    op.alter_column('aim2_record_base', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'aim1_record_base', type_='foreignkey')
    op.alter_column('aim1_record_base', 'etl_run_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
