"""getting db back to analysis etl state

Revision ID: 20dedc50864f
Revises: 923d39b6c4da
Create Date: 2026-02-19 13:36:08.337365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '20dedc50864f'
down_revision: Union[str, Sequence[str], None] = '923d39b6c4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('observation_unique_key'), 'observation', type_='unique')
    op.create_unique_constraint('observation_unique_key', 'observation', ['record_id', 'record_type', 'parameter_id', 'unit_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('observation_unique_key', 'observation', type_='unique')
    op.create_unique_constraint(op.f('observation_unique_key'), 'observation', ['record_id', 'record_type', 'parameter_id', 'unit_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
