"""Fixed alembic environment to import generated schemas again

Revision ID: 2b41e390fc5d
Revises: a8a3ea954e88
Create Date: 2026-01-07 18:18:18.527886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b41e390fc5d'
down_revision: Union[str, Sequence[str], None] = 'a8a3ea954e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
