"""Set geom as identifier for Polygon and inherit from BaseEntity

Revision ID: 4f28299e735d
Revises: fa2a3ff24010
Create Date: 2026-01-20 14:11:52.720427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f28299e735d'
down_revision: Union[str, Sequence[str], None] = 'fa2a3ff24010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('infrastructure_combustion_plants', 'geom',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('infrastructure_district_energy_systems', 'geom',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('infrastructure_food_processing_facilities', 'geom',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('infrastructure_msw_to_energy_anaerobic_digesters', 'geom',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('polygon', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('polygon', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('polygon', sa.Column('etl_run_id', sa.Integer(), nullable=True))
    op.add_column('polygon', sa.Column('lineage_group_id', sa.Integer(), nullable=True))
    op.alter_column('polygon', 'geom',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_polygon_geom', 'polygon', ['geom'])
    op.create_foreign_key(None, 'polygon', 'etl_run', ['etl_run_id'], ['id'])

    op.drop_constraint(op.f('landiq_record_polygon_id_fkey'), 'landiq_record', type_='foreignkey')
    op.alter_column('landiq_record', 'polygon_id',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_foreign_key(None, 'landiq_record', 'polygon', ['polygon_id'], ['geom'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'polygon', type_='foreignkey')
    op.drop_constraint('uq_polygon_geom', 'polygon', type_='unique')
    op.alter_column('polygon', 'geom',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('polygon', 'lineage_group_id')
    op.drop_column('polygon', 'etl_run_id')
    op.drop_column('polygon', 'updated_at')
    op.drop_column('polygon', 'created_at')
    op.drop_constraint(None, 'landiq_record', type_='foreignkey')
    op.create_foreign_key(op.f('landiq_record_polygon_id_fkey'), 'landiq_record', 'polygon', ['polygon_id'], ['id'])
    op.alter_column('landiq_record', 'polygon_id',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('infrastructure_msw_to_energy_anaerobic_digesters', 'geom',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('infrastructure_food_processing_facilities', 'geom',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('infrastructure_district_energy_systems', 'geom',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('infrastructure_combustion_plants', 'geom',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
