"""Remove diagnostic testing column

Revision ID: 5194157ee6f3
Revises: 5bc682554f31
Create Date: 2026-02-04 20:11:47.882909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5194157ee6f3'
down_revision: Union[str, Sequence[str], None] = '5bc682554f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landiq_record', 'testing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landiq_record', sa.Column('testing', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
