"""Initial migration

Revision ID: 5632747ee5fe
Revises: 1e9784d75e62
Create Date: 2025-12-16 04:39:20.946195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5632747ee5fe'
down_revision: Union[str, Sequence[str], None] = '1e9784d75e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landiq_record', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landiq_record', sa.Column('test', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
