"""Add fermentation method fields, resource_image, and county_ag_report_record tables

Revision ID: 563edbd884eb
Revises: 9e8f7a6b5c52
Create Date: 2026-04-09 09:30:47.898353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '563edbd884eb'
down_revision: Union[str, Sequence[str], None] = '9e8f7a6b5c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Integer(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['etl_run_id'], ['etl_run.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('county_ag_report_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Integer(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.Column('record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('prepared_sample_id', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_no', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_total', sa.Integer(), nullable=True),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('analyst_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('qc_pass', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_ag_product_id', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('produced_nsjv', sa.Boolean(), nullable=True),
    sa.Column('processed_nsjv', sa.Boolean(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prodn_value_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['analyst_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['etl_run_id'], ['etl_run.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.ForeignKeyConstraint(['method_id'], ['method.id'], ),
    sa.ForeignKeyConstraint(['prepared_sample_id'], ['prepared_sample.id'], ),
    sa.ForeignKeyConstraint(['primary_ag_product_id'], ['primary_ag_product.id'], ),
    sa.ForeignKeyConstraint(['raw_data_id'], ['file_object_metadata.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_foreign_key(None, 'fermentation_record', 'method', ['eh_method_id'], ['id'])
    op.create_foreign_key(None, 'fermentation_record', 'method', ['pretreatment_method_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fermentation_record', type_='foreignkey')
    op.drop_constraint(None, 'fermentation_record', type_='foreignkey')
    op.drop_table('county_ag_report_record')
    op.drop_table('resource_image')
    # ### end Alembic commands ###
