"""added test column to Resource

Revision ID: 5a6668dac367
Revises: 184417c6d044
Create Date: 2025-12-22 17:49:18.175092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6668dac367'
down_revision: Union[str, Sequence[str], None] = '184417c6d044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landiq_record', 'test')
    op.add_column('resource', sa.Column('test', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'test')
    op.add_column('landiq_record', sa.Column('test', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
