"""Add landiq_record_view automated v4

Revision ID: 60d284b1ce16
Revises: 90df744a03b4
Create Date: 2026-02-10 14:26:57.150476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d284b1ce16'
down_revision: Union[str, Sequence[str], None] = '90df744a03b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landiq_record_view',
    sa.Column('record_id', sa.Text(), nullable=True),
    sa.Column('geom', sa.Text(), nullable=True),
    sa.Column('geoid', sa.Text(), nullable=True),
    sa.Column('crop_name', sa.Text(), nullable=True),
    sa.Column('acres', sa.Float(), nullable=True),
    sa.Column('irrigated', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Integer(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['etl_run_id'], ['etl_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('landiq_record_view')
    # ### end Alembic commands ###
