"""adding landiq_resource_mapping import to ca_biositing.py

Revision ID: 62e3c4873fe4
Revises: c3f69dd5276b
Create Date: 2026-02-10 12:47:47.698649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e3c4873fe4'
down_revision: Union[str, Sequence[str], None] = 'c3f69dd5276b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landiq_resource_mapping',
    sa.Column('landiq_crop_name', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Integer(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['etl_run_id'], ['etl_run.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('landiq_resource_mapping')
    # ### end Alembic commands ###
