"""Add vessel_id FK to fermentation_record

Revision ID: 6d051c894fbb
Revises: 311148551786
Create Date: 2026-02-19 16:03:00.448657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6d051c894fbb'
down_revision: Union[str, Sequence[str], None] = '311148551786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'fermentation_record', 'decon_vessel', ['vessel_id'], ['id'])
    op.alter_column('usda_survey_record', 'begin_code',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('usda_survey_record', 'end_code',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usda_survey_record', 'end_code',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('usda_survey_record', 'begin_code',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'fermentation_record', type_='foreignkey')
    # ### end Alembic commands ###
