"""added some new columns to FermentationRecord again

Revision ID: 7a1a07ff85b0
Revises: 6d051c894fbb
Create Date: 2026-02-19 16:22:29.081334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1a07ff85b0'
down_revision: Union[str, Sequence[str], None] = '6d051c894fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fermentation_record', sa.Column('reaction_volume_L', sa.Numeric(), nullable=True))
    op.add_column('fermentation_record', sa.Column('inoculum_volume_L', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fermentation_record', 'inoculum_volume_L')
    op.drop_column('fermentation_record', 'reaction_volume_L')
    # ### end Alembic commands ###
