"""Detect model changes after fixing Alembic environment

Revision ID: 7d3c4134d5eb
Revises: 09daa1ad6e0b
Create Date: 2025-10-24 19:54:09.896063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3c4134d5eb'
down_revision: Union[str, Sequence[str], None] = '09daa1ad6e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
