"""Remove identifier: true from LandiqRecord.record_id to fix composite PK

Revision ID: 8da4b5cf5e63
Revises: 5194157ee6f3
Create Date: 2026-02-04 20:41:13.777145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da4b5cf5e63'
down_revision: Union[str, Sequence[str], None] = '5194157ee6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
