"""Finally detect biomass_test column

Revision ID: 8de419051d03
Revises: 7d3c4134d5eb
Create Date: 2025-10-24 20:08:00.485037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de419051d03'
down_revision: Union[str, Sequence[str], None] = '7d3c4134d5eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biomass', sa.Column('biomass_test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biomass', 'biomass_test')
    # ### end Alembic commands ###
