"""add uri to file_object_metadata

Revision ID: 923d39b6c4da
Revises: 9c5c72c6d059
Create Date: 2026-02-18 13:20:13.029272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '923d39b6c4da'
down_revision: Union[str, Sequence[str], None] = '9c5c72c6d059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_object_metadata', sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(None, 'file_object_metadata', ['uri'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file_object_metadata', type_='unique')
    op.drop_column('file_object_metadata', 'uri')
    # ### end Alembic commands ###
