"""adding full address to location_address

Revision ID: 9809213445bb
Revises: 7a1c996e0a6c
Create Date: 2026-01-30 14:21:05.418178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9809213445bb'
down_revision: Union[str, Sequence[str], None] = '7a1c996e0a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('unique_record_id'), table_name='landiq_record')
    op.add_column('location_address', sa.Column('full_address', sa.Text(), nullable=True))
    #op.drop_index(op.f('unique_geom_dataset_md5'), table_name='polygon')
    op.add_column('provider', sa.Column('type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'type')
    #op.create_index(op.f('unique_geom_dataset_md5'), 'polygon', [sa.literal_column('md5(geom)'), 'dataset_id'], unique=True)
    op.drop_column('location_address', 'full_address')
    #op.create_index(op.f('unique_record_id'), 'landiq_record', ['record_id'], unique=True)
    # ### end Alembic commands ###
