"""testing linkml created python object creation

Revision ID: 99af25a3b574
Revises: 38398b232319
Create Date: 2025-10-30 16:38:00.752859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99af25a3b574'
down_revision: Union[str, Sequence[str], None] = '38398b232319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Geography',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_name', sa.Text(), nullable=True),
    sa.Column('state_fips', sa.Text(), nullable=True),
    sa.Column('county_name', sa.Text(), nullable=True),
    sa.Column('county_fips', sa.Text(), nullable=True),
    sa.Column('geoid', sa.Text(), nullable=True),
    sa.Column('region_name', sa.Text(), nullable=True),
    sa.Column('agg_level_desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CensusRecord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('crop', sa.Enum('Almond', 'Pistachio', 'Tomato', 'Olive', name='CropEnum'), nullable=True),
    sa.Column('variable', sa.Enum('ACREAGE_TOTAL', 'ACREAGE_BEARING', 'ACREAGE_NONBEARING', 'YIELD', 'PRODUCTION', 'OPERATIONS', name='VariableEnum'), nullable=True),
    sa.Column('unit', sa.Enum('ACRES', 'TONS', 'TONS_PER_ACRE', 'OPERATIONS', name='UnitEnum'), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('bearing_status', sa.Enum('BEARING', 'NONBEARING', 'NA', name='BearingStatusEnum'), nullable=True),
    sa.Column('class_desc', sa.Text(), nullable=True),
    sa.Column('domain_desc', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('geography_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['geography_id'], ['Geography.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SurveyRecord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_desc', sa.Text(), nullable=True),
    sa.Column('freq_desc', sa.Text(), nullable=True),
    sa.Column('program_desc', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('crop', sa.Enum('Almond', 'Pistachio', 'Tomato', 'Olive', name='CropEnum'), nullable=True),
    sa.Column('variable', sa.Enum('ACREAGE_TOTAL', 'ACREAGE_BEARING', 'ACREAGE_NONBEARING', 'YIELD', 'PRODUCTION', 'OPERATIONS', name='VariableEnum'), nullable=True),
    sa.Column('unit', sa.Enum('ACRES', 'TONS', 'TONS_PER_ACRE', 'OPERATIONS', name='UnitEnum'), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('bearing_status', sa.Enum('BEARING', 'NONBEARING', 'NA', name='BearingStatusEnum'), nullable=True),
    sa.Column('class_desc', sa.Text(), nullable=True),
    sa.Column('domain_desc', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('geography_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['geography_id'], ['Geography.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('USDARecord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('crop', sa.Enum('Almond', 'Pistachio', 'Tomato', 'Olive', name='CropEnum'), nullable=True),
    sa.Column('variable', sa.Enum('ACREAGE_TOTAL', 'ACREAGE_BEARING', 'ACREAGE_NONBEARING', 'YIELD', 'PRODUCTION', 'OPERATIONS', name='VariableEnum'), nullable=True),
    sa.Column('unit', sa.Enum('ACRES', 'TONS', 'TONS_PER_ACRE', 'OPERATIONS', name='UnitEnum'), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('bearing_status', sa.Enum('BEARING', 'NONBEARING', 'NA', name='BearingStatusEnum'), nullable=True),
    sa.Column('class_desc', sa.Text(), nullable=True),
    sa.Column('domain_desc', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('geography_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['geography_id'], ['Geography.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('USDARecord')
    op.drop_table('SurveyRecord')
    op.drop_table('CensusRecord')
    op.drop_table('Geography')
    # ### end Alembic commands ###
