"""usda_etl_model_updates

Revision ID: a085cd4a462e
Revises: f5c8c031aef9
Create Date: 2026-02-12 16:21:36.347658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a085cd4a462e'
down_revision: Union[str, Sequence[str], None] = 'f5c8c031aef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('observation_record_id_key'), 'observation', type_='unique')
    op.create_unique_constraint('observation_unique_key', 'observation', ['record_id', 'record_type', 'parameter_id', 'unit_id'])
    op.add_column('usda_commodity', sa.Column('api_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('usda_commodity', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('usda_commodity', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('usda_survey_record', sa.Column('begin_code', sa.Integer(), nullable=True))
    op.add_column('usda_survey_record', sa.Column('end_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # Data migration: Seed California state + target counties for ETL pipelines
    op.execute("""
        INSERT INTO place (geoid, state_name, state_fips, county_name, county_fips, agg_level_desc)
        VALUES
          ('06000', 'CALIFORNIA', '06', NULL, '000', 'STATE'),
          ('06077', 'CALIFORNIA', '06', 'SAN JOAQUIN', '077', 'COUNTY'),
          ('06099', 'CALIFORNIA', '06', 'STANISLAUS', '099', 'COUNTY'),
          ('06047', 'CALIFORNIA', '06', 'MERCED', '047', 'COUNTY')
        ON CONFLICT (geoid) DO NOTHING
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usda_survey_record', 'end_code')
    op.drop_column('usda_survey_record', 'begin_code')
    op.drop_column('usda_commodity', 'updated_at')
    op.drop_column('usda_commodity', 'created_at')
    op.drop_column('usda_commodity', 'api_name')
    op.drop_constraint('observation_unique_key', 'observation', type_='unique')
    op.create_unique_constraint(op.f('observation_record_id_key'), 'observation', ['record_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###

    # Note: Place records are not removed on downgrade as they may be referenced by other data
