"""Add ResidueFactor model with unique constraint

Revision ID: a721de1a5850
Revises: bd227e99e006
Create Date: 2026-04-14 15:33:26.629031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a721de1a5850'
down_revision: Union[str, Sequence[str], None] = 'd2b6b2a7c9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residue_factor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Integer(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('factor_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('factor_min', sa.Numeric(), nullable=True),
    sa.Column('factor_max', sa.Numeric(), nullable=True),
    sa.Column('factor_mid', sa.Numeric(), nullable=True),
    sa.Column('prune_trim_yield', sa.Numeric(), nullable=True),
    sa.Column('prune_trim_yield_unit_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['etl_run_id'], ['etl_run.id'], ),
    sa.ForeignKeyConstraint(['prune_trim_yield_unit_id'], ['unit.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'factor_type', name='uq_residue_factor_resource_id_factor_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('residue_factor')
    # ### end Alembic commands ###
