"""update_mv_biomass_composition

Revision ID: b695bb1dbf9f
Revises: f5fe3dab0af2
Create Date: 2026-03-09 08:37:44.649510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from ca_biositing.datamodels.data_portal_views import mv_biomass_composition


# revision identifiers, used by Alembic.
revision: str = 'b695bb1dbf9f'
down_revision: Union[str, Sequence[str], None] = 'f5fe3dab0af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the existing view and index
    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_composition CASCADE")

    # Recreate the view with the new definition
    compiled = mv_biomass_composition.compile(dialect=sa.dialects.postgresql.dialect(), compile_kwargs={"literal_binds": True})
    op.execute(f"CREATE MATERIALIZED VIEW data_portal.mv_biomass_composition AS {compiled}")

    # Recreate the unique index
    # Note: The key now includes 'unit' as well, although resource_id + analysis_type + parameter_name + unit might be the unique constraint now
    # Or maybe just resource_id + analysis_type + parameter_name is still unique if unit is consistent per parameter?
    # Let's assume (resource_id, analysis_type, parameter_name, unit) is the unique key now to be safe, or just (resource_id, analysis_type, parameter_name) if we are sure.
    # Given the query groups by unit as well, we should include it in the index.
    op.execute("CREATE UNIQUE INDEX idx_mv_biomass_composition_key ON data_portal.mv_biomass_composition (resource_id, analysis_type, parameter_name, unit)")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the new view
    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_composition CASCADE")

    # We would ideally restore the old view definition here, but for now we'll just leave it dropped
    # or we could try to reconstruct the old query.
    # Since this is a dev iteration, dropping is often acceptable, or we can just say we can't easily downgrade to the exact previous state without the old query code.
    # But let's try to be nice and at least clean up.

    # ### end Alembic commands ###
