"""Add fermentation method fields, resource_image, and county_ag_report_record tables

Revision ID: bd227e99e006
Revises: 9e8f7a6b5c52
Create Date: 2026-04-09 14:09:11.091043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bd227e99e006'
down_revision: Union[str, Sequence[str], None] = '9e8f7a6b5c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Integer(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['etl_run_id'], ['etl_run.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'image_url', name='resource_image_resource_id_image_url_key')
    )
    op.create_table('county_ag_report_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Integer(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.Column('record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('geoid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_ag_product_id', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('produced_nsjv', sa.Boolean(), nullable=True),
    sa.Column('processed_nsjv', sa.Boolean(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prodn_value_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['etl_run_id'], ['etl_run.id'], ),
    sa.ForeignKeyConstraint(['geoid'], ['place.geoid'], ),
    sa.ForeignKeyConstraint(['primary_ag_product_id'], ['primary_ag_product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_foreign_key('fermentation_record_pretreatment_method_id_fkey', 'fermentation_record', 'method', ['pretreatment_method_id'], ['id'])
    op.create_foreign_key('fermentation_record_eh_method_id_fkey', 'fermentation_record', 'method', ['eh_method_id'], ['id'])
    op.create_foreign_key('fermentation_record_strain_id_fkey', 'fermentation_record', 'strain', ['strain_id'], ['id'])
    op.create_unique_constraint('strain_name_key', 'strain', ['name'])
    op.add_column('method', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('fermentation_record', sa.Column('bioconversion_method_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fermentation_record_bioconversion_method_id_fkey', 'fermentation_record', 'method', ['bioconversion_method_id'], ['id'])

    op.execute("DROP INDEX IF EXISTS data_portal.idx_mv_biomass_fermentation_resource_strain")
    op.execute("DROP INDEX IF EXISTS data_portal.idx_mv_biomass_fermentation_product_name")
    op.execute("DROP INDEX IF EXISTS data_portal.idx_mv_biomass_fermentation_strain_name")
    op.execute("DROP INDEX IF EXISTS data_portal.idx_mv_biomass_fermentation_county")
    op.execute("DROP INDEX IF EXISTS data_portal.idx_mv_biomass_fermentation_geoid")
    op.execute("DROP INDEX IF EXISTS data_portal.idx_mv_biomass_fermentation_resource_id")
    op.execute("DROP INDEX IF EXISTS data_portal.idx_mv_biomass_fermentation_id")

    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_fermentation CASCADE")
    op.execute("""
        CREATE MATERIALIZED VIEW data_portal.mv_biomass_fermentation AS
        SELECT row_number() OVER (ORDER BY fermentation_record.resource_id, location_address.geography_id, strain.name, pm.name, em.name, bm.name, parameter.name, unit.name) AS id,
               fermentation_record.resource_id,
               resource.name AS resource_name,
               location_address.geography_id AS geoid,
               place.county_name AS county,
               strain.name AS strain_name,
               pm.name AS pretreatment_method,
               em.name AS enzyme_name,
               bm.name AS bioconversion_method,
               coalesce(pm.duration, em.duration, bm.duration) AS elapsed_time,
               parameter.name AS product_name,
               avg(observation.value) AS avg_value,
               min(observation.value) AS min_value,
               max(observation.value) AS max_value,
               stddev(observation.value) AS std_dev,
               count(*) AS observation_count,
               unit.name AS unit
        FROM fermentation_record
        JOIN resource ON fermentation_record.resource_id = resource.id
        LEFT OUTER JOIN prepared_sample ON fermentation_record.prepared_sample_id = prepared_sample.id
        LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id
        LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
        LEFT OUTER JOIN place ON location_address.geography_id = place.geoid
        LEFT OUTER JOIN strain ON fermentation_record.strain_id = strain.id
        LEFT OUTER JOIN method AS pm ON fermentation_record.pretreatment_method_id = pm.id
        LEFT OUTER JOIN method AS em ON fermentation_record.eh_method_id = em.id
        LEFT OUTER JOIN method AS bm ON fermentation_record.bioconversion_method_id = bm.id
        JOIN observation ON lower(observation.record_id) = lower(fermentation_record.record_id)
        JOIN parameter ON observation.parameter_id = parameter.id
        LEFT OUTER JOIN unit ON observation.unit_id = unit.id
        WHERE fermentation_record.qc_pass != 'fail'
        GROUP BY fermentation_record.resource_id,
                 resource.name,
                 location_address.geography_id,
                 place.county_name,
                 strain.name,
                 pm.name,
                 em.name,
                 bm.name,
                 coalesce(pm.duration, em.duration, bm.duration),
                 parameter.name,
                 unit.name
    """)

    op.execute("""CREATE UNIQUE INDEX idx_mv_biomass_fermentation_id ON data_portal.mv_biomass_fermentation (id)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_resource_id ON data_portal.mv_biomass_fermentation (resource_id)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_geoid ON data_portal.mv_biomass_fermentation (geoid)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_county ON data_portal.mv_biomass_fermentation (county)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_strain_name ON data_portal.mv_biomass_fermentation (strain_name)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_product_name ON data_portal.mv_biomass_fermentation (product_name)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_resource_strain ON data_portal.mv_biomass_fermentation (resource_id, strain_name)""")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS data_portal.idx_mv_biomass_fermentation_resource_strain")
    op.execute("DROP INDEX IF EXISTS data_portal.idx_mv_biomass_fermentation_product_name")
    op.execute("DROP INDEX IF EXISTS data_portal.idx_mv_biomass_fermentation_strain_name")
    op.execute("DROP INDEX IF EXISTS data_portal.idx_mv_biomass_fermentation_county")
    op.execute("DROP INDEX IF EXISTS data_portal.idx_mv_biomass_fermentation_geoid")
    op.execute("DROP INDEX IF EXISTS data_portal.idx_mv_biomass_fermentation_resource_id")
    op.execute("DROP INDEX IF EXISTS data_portal.idx_mv_biomass_fermentation_id")

    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_fermentation CASCADE")
    op.execute("""
        CREATE MATERIALIZED VIEW data_portal.mv_biomass_fermentation AS
        SELECT row_number() OVER (ORDER BY fermentation_record.resource_id, location_address.geography_id, strain.name, pm.name, em.name, parameter.name, unit.name) AS id,
               fermentation_record.resource_id,
               resource.name AS resource_name,
               location_address.geography_id AS geoid,
               place.county_name AS county,
               strain.name AS strain_name,
               pm.name AS pretreatment_method,
               em.name AS enzyme_name,
               parameter.name AS product_name,
               avg(observation.value) AS avg_value,
               min(observation.value) AS min_value,
               max(observation.value) AS max_value,
               stddev(observation.value) AS std_dev,
               count(*) AS observation_count,
               unit.name AS unit
        FROM fermentation_record
        JOIN resource ON fermentation_record.resource_id = resource.id
        LEFT OUTER JOIN prepared_sample ON fermentation_record.prepared_sample_id = prepared_sample.id
        LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id
        LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
        LEFT OUTER JOIN place ON location_address.geography_id = place.geoid
        LEFT OUTER JOIN strain ON fermentation_record.strain_id = strain.id
        LEFT OUTER JOIN method AS pm ON fermentation_record.pretreatment_method_id = pm.id
        LEFT OUTER JOIN method AS em ON fermentation_record.eh_method_id = em.id
        JOIN observation ON lower(observation.record_id) = lower(fermentation_record.record_id)
        JOIN parameter ON observation.parameter_id = parameter.id
        LEFT OUTER JOIN unit ON observation.unit_id = unit.id
        WHERE fermentation_record.qc_pass != 'fail'
        GROUP BY fermentation_record.resource_id,
                 resource.name,
                 location_address.geography_id,
                 place.county_name,
                 strain.name,
                 pm.name,
                 em.name,
                 parameter.name,
                 unit.name
    """)

    op.execute("""CREATE UNIQUE INDEX idx_mv_biomass_fermentation_id ON data_portal.mv_biomass_fermentation (id)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_resource_id ON data_portal.mv_biomass_fermentation (resource_id)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_geoid ON data_portal.mv_biomass_fermentation (geoid)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_county ON data_portal.mv_biomass_fermentation (county)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_strain_name ON data_portal.mv_biomass_fermentation (strain_name)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_product_name ON data_portal.mv_biomass_fermentation (product_name)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_resource_strain ON data_portal.mv_biomass_fermentation (resource_id, strain_name)""")

    op.drop_constraint('fermentation_record_bioconversion_method_id_fkey', 'fermentation_record', type_='foreignkey')
    op.drop_column('fermentation_record', 'bioconversion_method_id')
    op.drop_column('method', 'duration')
    op.drop_constraint('strain_name_key', 'strain', type_='unique')
    op.drop_constraint('fermentation_record_strain_id_fkey', 'fermentation_record', type_='foreignkey')
    op.drop_constraint('fermentation_record_pretreatment_method_id_fkey', 'fermentation_record', type_='foreignkey')
    op.drop_constraint('fermentation_record_eh_method_id_fkey', 'fermentation_record', type_='foreignkey')
    op.drop_table('county_ag_report_record')
    op.drop_table('resource_image')
    # ### end Alembic commands ###
