"""Set record_id as identifier for Observation

Revision ID: d9b78cc21305
Revises: 660676b973c3
Create Date: 2026-01-18 14:18:28.856330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b78cc21305'
down_revision: Union[str, Sequence[str], None] = '660676b973c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aim1_record_base', 'record_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_aim1_record_base_record_id', 'aim1_record_base', ['record_id'])
    op.alter_column('aim2_record_base', 'record_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_aim2_record_base_record_id', 'aim2_record_base', ['record_id'])
    op.alter_column('autoclave_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_autoclave_record_record_id', 'autoclave_record', ['record_id'])
    op.alter_column('calorimetry_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_calorimetry_record_record_id', 'calorimetry_record', ['record_id'])
    op.alter_column('compositional_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_compositional_record_record_id', 'compositional_record', ['record_id'])
    op.alter_column('fermentation_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_fermentation_record_record_id', 'fermentation_record', ['record_id'])
    op.alter_column('ftnir_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_ftnir_record_record_id', 'ftnir_record', ['record_id'])
    op.alter_column('gasification_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_gasification_record_record_id', 'gasification_record', ['record_id'])
    op.alter_column('icp_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_icp_record_record_id', 'icp_record', ['record_id'])
    op.alter_column('observation', 'record_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_observation_record_id', 'observation', ['record_id'])
    op.alter_column('pretreatment_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_pretreatment_record_record_id', 'pretreatment_record', ['record_id'])
    op.alter_column('proximate_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_proximate_record_record_id', 'proximate_record', ['record_id'])
    op.alter_column('rgb_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_rgb_record_record_id', 'rgb_record', ['record_id'])
    op.alter_column('ultimate_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_ultimate_record_record_id', 'ultimate_record', ['record_id'])
    op.alter_column('xrd_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_xrd_record_record_id', 'xrd_record', ['record_id'])
    op.alter_column('xrf_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_xrf_record_record_id', 'xrf_record', ['record_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_xrf_record_record_id', 'xrf_record', type_='unique')
    op.alter_column('xrf_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_xrd_record_record_id', 'xrd_record', type_='unique')
    op.alter_column('xrd_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_ultimate_record_record_id', 'ultimate_record', type_='unique')
    op.alter_column('ultimate_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_rgb_record_record_id', 'rgb_record', type_='unique')
    op.alter_column('rgb_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_proximate_record_record_id', 'proximate_record', type_='unique')
    op.alter_column('proximate_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_pretreatment_record_record_id', 'pretreatment_record', type_='unique')
    op.alter_column('pretreatment_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_observation_record_id', 'observation', type_='unique')
    op.alter_column('observation', 'record_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_icp_record_record_id', 'icp_record', type_='unique')
    op.alter_column('icp_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_gasification_record_record_id', 'gasification_record', type_='unique')
    op.alter_column('gasification_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_ftnir_record_record_id', 'ftnir_record', type_='unique')
    op.alter_column('ftnir_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_fermentation_record_record_id', 'fermentation_record', type_='unique')
    op.alter_column('fermentation_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_compositional_record_record_id', 'compositional_record', type_='unique')
    op.alter_column('compositional_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_calorimetry_record_record_id', 'calorimetry_record', type_='unique')
    op.alter_column('calorimetry_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_autoclave_record_record_id', 'autoclave_record', type_='unique')
    op.alter_column('autoclave_record', 'record_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_aim2_record_base_record_id', 'aim2_record_base', type_='unique')
    op.alter_column('aim2_record_base', 'record_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_aim1_record_base_record_id', 'aim1_record_base', type_='unique')
    op.alter_column('aim1_record_base', 'record_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
