"""Initial migration

Revision ID: e22149be0d9c
Revises:
Create Date: 2025-12-08 18:01:48.554213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e22149be0d9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AgTreatment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Aim1RecordBase',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_no', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_total', sa.Integer(), nullable=True),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('qc_pass', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Aim2RecordBase',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('analyst_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('qc_pass', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('technical_replicate_total', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_no', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AnalysisType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AutoclaveRecord',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('analyst_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('qc_pass', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('technical_replicate_total', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_no', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BaseEntity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BillionTon2023Record',
    sa.Column('subclass_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('geoid', sa.Text(), nullable=True),
    sa.Column('county_square_miles', sa.Float(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('scenario_name', sa.Text(), nullable=True),
    sa.Column('price_offered_usd', sa.Numeric(), nullable=True),
    sa.Column('production', sa.Integer(), nullable=True),
    sa.Column('production_unit_id', sa.Integer(), nullable=True),
    sa.Column('btu_ton', sa.Integer(), nullable=True),
    sa.Column('production_energy_content', sa.Integer(), nullable=True),
    sa.Column('energy_content_unit_id', sa.Integer(), nullable=True),
    sa.Column('product_density_dtpersqmi', sa.Numeric(), nullable=True),
    sa.Column('land_source', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CalorimetryRecord',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_no', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_total', sa.Integer(), nullable=True),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('qc_pass', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CollectionMethod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CompositionalRecord',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_no', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_total', sa.Integer(), nullable=True),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('qc_pass', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('affiliation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DataSource',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DataSourceType',
    sa.Column('source_type_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Dataset',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('record_type', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DimensionType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EntityLineage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.Column('source_table', sa.Text(), nullable=True),
    sa.Column('source_row_id', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Equipment',
    sa.Column('equipment_location_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EtlRun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('pipeline_name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('records_ingested', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Experiment',
    sa.Column('analyst_id', sa.Integer(), nullable=True),
    sa.Column('exper_start_date', sa.Date(), nullable=True),
    sa.Column('exper_duration', sa.Numeric(), nullable=True),
    sa.Column('exper_duration_unit_id', sa.Integer(), nullable=True),
    sa.Column('exper_location_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ExperimentAnalysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('analysis_type_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ExperimentEquipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ExperimentMethod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ExperimentPreparedSample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('prepared_sample_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FermentationRecord',
    sa.Column('strain_id', sa.Integer(), nullable=True),
    sa.Column('pretreatment_method_id', sa.Integer(), nullable=True),
    sa.Column('eh_method_id', sa.Integer(), nullable=True),
    sa.Column('replicate_no', sa.Integer(), nullable=True),
    sa.Column('well_position', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Numeric(), nullable=True),
    sa.Column('agitation_rpm', sa.Numeric(), nullable=True),
    sa.Column('vessel_id', sa.Integer(), nullable=True),
    sa.Column('analyte_detection_equipment_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('analyst_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('qc_pass', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('technical_replicate_total', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_no', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FieldSample',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('collector_id', sa.Integer(), nullable=True),
    sa.Column('sample_collection_source', sa.Text(), nullable=True),
    sa.Column('amount_collected', sa.Numeric(), nullable=True),
    sa.Column('amount_collected_unit_id', sa.Integer(), nullable=True),
    sa.Column('sampling_location_id', sa.Integer(), nullable=True),
    sa.Column('field_storage_method_id', sa.Integer(), nullable=True),
    sa.Column('field_storage_duration_value', sa.Numeric(), nullable=True),
    sa.Column('field_storage_duration_unit_id', sa.Integer(), nullable=True),
    sa.Column('field_storage_location_id', sa.Integer(), nullable=True),
    sa.Column('collection_timestamp', sa.DateTime(), nullable=True),
    sa.Column('collection_method_id', sa.Integer(), nullable=True),
    sa.Column('harvest_method_id', sa.Integer(), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('field_sample_storage_location_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FieldSampleCondition',
    sa.Column('field_sample_id', sa.Integer(), nullable=True),
    sa.Column('ag_treatment_id', sa.Integer(), nullable=True),
    sa.Column('last_application_date', sa.Date(), nullable=True),
    sa.Column('treatment_amount_per_acre', sa.Float(), nullable=True),
    sa.Column('processing_method_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FieldStorageMethod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FileObjectMetadata',
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('bucket_path', sa.Text(), nullable=True),
    sa.Column('file_format', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('checksum_md5', sa.Text(), nullable=True),
    sa.Column('checksum_sha256', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FtnirRecord',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_no', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_total', sa.Integer(), nullable=True),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('qc_pass', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GasificationRecord',
    sa.Column('feedstock_mass', sa.Numeric(), nullable=True),
    sa.Column('bed_temperature', sa.Numeric(), nullable=True),
    sa.Column('gas_flow_rate', sa.Numeric(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('analyst_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('qc_pass', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('technical_replicate_total', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_no', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Geography',
    sa.Column('geoid', sa.Text(), nullable=False),
    sa.Column('state_name', sa.Text(), nullable=True),
    sa.Column('state_fips', sa.Text(), nullable=True),
    sa.Column('county_name', sa.Text(), nullable=True),
    sa.Column('county_fips', sa.Text(), nullable=True),
    sa.Column('region_name', sa.Text(), nullable=True),
    sa.Column('agg_level_desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('geoid')
    )
    op.create_table('HarvestMethod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IcpRecord',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_no', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_total', sa.Integer(), nullable=True),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('qc_pass', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LandiqRecord',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('polygon_id', sa.Integer(), nullable=True),
    sa.Column('main_crop', sa.Integer(), nullable=True),
    sa.Column('secondary_crop', sa.Integer(), nullable=True),
    sa.Column('tertiary_crop', sa.Integer(), nullable=True),
    sa.Column('quaternary_crop', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('irrigated', sa.Boolean(), nullable=True),
    sa.Column('acres', sa.Float(), nullable=True),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LineageGroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LocationAddress',
    sa.Column('geography_id', sa.Text(), nullable=True),
    sa.Column('address_line1', sa.Text(), nullable=True),
    sa.Column('address_line2', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('zip', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LocationResolution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LocationSoilType',
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('soil_type_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LookupBase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Method',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('method_abbrev_id', sa.Integer(), nullable=True),
    sa.Column('method_category_id', sa.Integer(), nullable=True),
    sa.Column('method_standard_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detection_limits', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MethodAbbrev',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MethodCategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MethodStandard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Observation',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.Text(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('parameter_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('dimension_type_id', sa.Integer(), nullable=True),
    sa.Column('dimension_value', sa.Numeric(), nullable=True),
    sa.Column('dimension_unit_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Parameter',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('standard_unit_id', sa.Integer(), nullable=True),
    sa.Column('calculated', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ParameterCategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ParameterCategoryParameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=True),
    sa.Column('parameter_category_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ParameterUnit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=True),
    sa.Column('alternate_unit_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PhysicalCharacteristic',
    sa.Column('field_sample_id', sa.Integer(), nullable=True),
    sa.Column('particle_length', sa.Numeric(), nullable=True),
    sa.Column('particle_width', sa.Numeric(), nullable=True),
    sa.Column('particle_height', sa.Numeric(), nullable=True),
    sa.Column('particle_unit_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Polygon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geoid', sa.Text(), nullable=True),
    sa.Column('geom', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PreparationMethod',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prep_method_abbrev_id', sa.Integer(), nullable=True),
    sa.Column('prep_temp_c', sa.Numeric(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('drying_step', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PreparationMethodAbbreviation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PreparedSample',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('field_sample_id', sa.Integer(), nullable=True),
    sa.Column('prep_method_id', sa.Integer(), nullable=True),
    sa.Column('prep_date', sa.Date(), nullable=True),
    sa.Column('preparer_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PretreatmentRecord',
    sa.Column('pretreatment_method_id', sa.Integer(), nullable=True),
    sa.Column('eh_method_id', sa.Integer(), nullable=True),
    sa.Column('reaction_block_id', sa.Integer(), nullable=True),
    sa.Column('block_position', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Numeric(), nullable=True),
    sa.Column('replicate_no', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('analyst_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('qc_pass', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('technical_replicate_total', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_no', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PrimaryCrop',
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProcessingMethod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codename', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProximateRecord',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_no', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_total', sa.Integer(), nullable=True),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('qc_pass', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Resource',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('primary_crop_id', sa.Integer(), nullable=True),
    sa.Column('resource_class_id', sa.Integer(), nullable=True),
    sa.Column('resource_subclass_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ResourceAvailability',
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('geoid', sa.Text(), nullable=True),
    sa.Column('from_month', sa.Integer(), nullable=True),
    sa.Column('to_month', sa.Integer(), nullable=True),
    sa.Column('year_round', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ResourceClass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ResourceCounterfactual',
    sa.Column('geoid', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('counterfactual_description', sa.Text(), nullable=True),
    sa.Column('animal_bedding_percent', sa.Numeric(), nullable=True),
    sa.Column('animal_bedding_source_id', sa.Integer(), nullable=True),
    sa.Column('animal_feed_percent', sa.Numeric(), nullable=True),
    sa.Column('animal_feed_source_id', sa.Integer(), nullable=True),
    sa.Column('bioelectricty_percent', sa.Numeric(), nullable=True),
    sa.Column('bioelectricty_source_id', sa.Integer(), nullable=True),
    sa.Column('burn_percent', sa.Numeric(), nullable=True),
    sa.Column('burn_source_id', sa.Integer(), nullable=True),
    sa.Column('compost_percent', sa.Numeric(), nullable=True),
    sa.Column('compost_source_id', sa.Integer(), nullable=True),
    sa.Column('landfill_percent', sa.Numeric(), nullable=True),
    sa.Column('landfill_source_id', sa.Integer(), nullable=True),
    sa.Column('counterfactual_date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ResourceMorphology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('morphology_uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ResourceSubclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ResourceUsdaCommodityMap',
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('primary_crop_id', sa.Integer(), nullable=True),
    sa.Column('usda_commodity_id', sa.Integer(), nullable=True),
    sa.Column('match_tier', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RgbRecord',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_no', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_total', sa.Integer(), nullable=True),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('qc_pass', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SoilType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SourceType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Strain',
    sa.Column('parent_strain_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UltimateRecord',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_no', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_total', sa.Integer(), nullable=True),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('qc_pass', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UsdaCensusRecord',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('geoid', sa.Text(), nullable=True),
    sa.Column('commodity_code', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UsdaCommodity',
    sa.Column('usda_source', sa.Text(), nullable=True),
    sa.Column('usda_code', sa.Text(), nullable=True),
    sa.Column('parent_commodity_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UsdaDomain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UsdaMarketRecord',
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('report_begin_date', sa.DateTime(), nullable=True),
    sa.Column('report_end_date', sa.DateTime(), nullable=True),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.Column('commodity_id', sa.Integer(), nullable=True),
    sa.Column('market_type_id', sa.Integer(), nullable=True),
    sa.Column('market_type_catagory', sa.Text(), nullable=True),
    sa.Column('grp', sa.Text(), nullable=True),
    sa.Column('market_catagory_id', sa.Integer(), nullable=True),
    sa.Column('class_', sa.Text(), nullable=True),
    sa.Column('grade', sa.Text(), nullable=True),
    sa.Column('variety', sa.Text(), nullable=True),
    sa.Column('protein_pct', sa.Numeric(), nullable=True),
    sa.Column('application', sa.Text(), nullable=True),
    sa.Column('pkg', sa.Text(), nullable=True),
    sa.Column('sale_type', sa.Text(), nullable=True),
    sa.Column('price_unit_id', sa.Integer(), nullable=True),
    sa.Column('freight', sa.Text(), nullable=True),
    sa.Column('trans_mode', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UsdaMarketReport',
    sa.Column('slug_id', sa.Integer(), nullable=True),
    sa.Column('slug_name', sa.Text(), nullable=True),
    sa.Column('report_series_title', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Text(), nullable=True),
    sa.Column('office_name', sa.Text(), nullable=True),
    sa.Column('office_city_id', sa.Integer(), nullable=True),
    sa.Column('office_state_fips', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UsdaStatisticCategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UsdaSurveyProgram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UsdaSurveyRecord',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('geoid', sa.Text(), nullable=True),
    sa.Column('commodity_code', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('survey_program_id', sa.Integer(), nullable=True),
    sa.Column('survey_period', sa.Text(), nullable=True),
    sa.Column('reference_month', sa.Text(), nullable=True),
    sa.Column('seasonal_flag', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UsdaTermMap',
    sa.Column('source_system', sa.Text(), nullable=True),
    sa.Column('source_context', sa.Text(), nullable=True),
    sa.Column('raw_term', sa.Text(), nullable=True),
    sa.Column('usda_commodity_id', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('XrdRecord',
    sa.Column('maybe_scan_low_nm', sa.Integer(), nullable=True),
    sa.Column('maybe_scan_high_nm', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_no', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_total', sa.Integer(), nullable=True),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('qc_pass', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('XrfRecord',
    sa.Column('maybe_wavelength_nm', sa.Numeric(), nullable=True),
    sa.Column('maybe_intensity', sa.Numeric(), nullable=True),
    sa.Column('maybe_energy_slope', sa.Numeric(), nullable=True),
    sa.Column('maybe_energy_offset', sa.Numeric(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_no', sa.Integer(), nullable=True),
    sa.Column('technical_replicate_total', sa.Integer(), nullable=True),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('qc_pass', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('XrfRecord')
    op.drop_table('XrdRecord')
    op.drop_table('UsdaTermMap')
    op.drop_table('UsdaSurveyRecord')
    op.drop_table('UsdaSurveyProgram')
    op.drop_table('UsdaStatisticCategory')
    op.drop_table('UsdaMarketReport')
    op.drop_table('UsdaMarketRecord')
    op.drop_table('UsdaDomain')
    op.drop_table('UsdaCommodity')
    op.drop_table('UsdaCensusRecord')
    op.drop_table('Unit')
    op.drop_table('UltimateRecord')
    op.drop_table('Strain')
    op.drop_table('SourceType')
    op.drop_table('SoilType')
    op.drop_table('RgbRecord')
    op.drop_table('ResourceUsdaCommodityMap')
    op.drop_table('ResourceSubclass')
    op.drop_table('ResourceMorphology')
    op.drop_table('ResourceCounterfactual')
    op.drop_table('ResourceClass')
    op.drop_table('ResourceAvailability')
    op.drop_table('Resource')
    op.drop_table('ProximateRecord')
    op.drop_table('Provider')
    op.drop_table('ProcessingMethod')
    op.drop_table('PrimaryCrop')
    op.drop_table('PretreatmentRecord')
    op.drop_table('PreparedSample')
    op.drop_table('PreparationMethodAbbreviation')
    op.drop_table('PreparationMethod')
    op.drop_table('Polygon')
    op.drop_table('PhysicalCharacteristic')
    op.drop_table('ParameterUnit')
    op.drop_table('ParameterCategoryParameter')
    op.drop_table('ParameterCategory')
    op.drop_table('Parameter')
    op.drop_table('Observation')
    op.drop_table('MethodStandard')
    op.drop_table('MethodCategory')
    op.drop_table('MethodAbbrev')
    op.drop_table('Method')
    op.drop_table('LookupBase')
    op.drop_table('LocationSoilType')
    op.drop_table('LocationResolution')
    op.drop_table('LocationAddress')
    op.drop_table('LineageGroup')
    op.drop_table('LandiqRecord')
    op.drop_table('IcpRecord')
    op.drop_table('HarvestMethod')
    op.drop_table('Geography')
    op.drop_table('GasificationRecord')
    op.drop_table('FtnirRecord')
    op.drop_table('FileObjectMetadata')
    op.drop_table('FieldStorageMethod')
    op.drop_table('FieldSampleCondition')
    op.drop_table('FieldSample')
    op.drop_table('FermentationRecord')
    op.drop_table('ExperimentPreparedSample')
    op.drop_table('ExperimentMethod')
    op.drop_table('ExperimentEquipment')
    op.drop_table('ExperimentAnalysis')
    op.drop_table('Experiment')
    op.drop_table('EtlRun')
    op.drop_table('Equipment')
    op.drop_table('EntityLineage')
    op.drop_table('DimensionType')
    op.drop_table('Dataset')
    op.drop_table('DataSourceType')
    op.drop_table('DataSource')
    op.drop_table('Contact')
    op.drop_table('CompositionalRecord')
    op.drop_table('CollectionMethod')
    op.drop_table('CalorimetryRecord')
    op.drop_table('BillionTon2023Record')
    op.drop_table('BaseEntity')
    op.drop_table('AutoclaveRecord')
    op.drop_table('AnalysisType')
    op.drop_table('Aim2RecordBase')
    op.drop_table('Aim1RecordBase')
    op.drop_table('AgTreatment')
    # ### end Alembic commands ###
