"""modifying the resource module to align with gsheet

Revision ID: e42f07cb43cf
Revises: fd64e8f83e51
Create Date: 2026-02-06 11:16:07.143873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42f07cb43cf'
down_revision: Union[str, Sequence[str], None] = 'fd64e8f83e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('resource_code', sa.Text(), nullable=True))
    op.add_column('resource', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('resource', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('resource', 'description')
    op.drop_column('resource', 'resource_code')
    # ### end Alembic commands ###
