"""making landiq_resource_mapping reference primary_ag_product

Revision ID: ea01391d34c3
Revises: 62e3c4873fe4
Create Date: 2026-02-10 13:04:59.026792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea01391d34c3'
down_revision: Union[str, Sequence[str], None] = '62e3c4873fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('landiq_resource_mapping', 'landiq_crop_name',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               postgresql_using='landiq_crop_name::integer',
               existing_nullable=True)
    op.create_foreign_key(None, 'landiq_resource_mapping', 'primary_ag_product', ['landiq_crop_name'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'landiq_resource_mapping', type_='foreignkey')
    op.alter_column('landiq_resource_mapping', 'landiq_crop_name',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
