"""add_data_portal_views

Revision ID: f5ac1b135099
Revises: 64de60aff03d
Create Date: 2026-03-08 23:03:39.654496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from ca_biositing.datamodels.data_portal_views import (
    mv_biomass_search,
    mv_biomass_composition,
    mv_biomass_county_production,
    mv_biomass_availability,
    mv_biomass_sample_stats,
    mv_biomass_fermentation,
    mv_biomass_gasification,
    mv_biomass_pricing
)


# revision identifiers, used by Alembic.
revision: str = 'f5ac1b135099'
down_revision: Union[str, Sequence[str], None] = '64de60aff03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def create_materialized_view(view_name, statement):
    """Create a materialized view."""
    # Compile the statement to SQL string
    # We need to bind it to the engine to get the correct dialect, but here we can assume postgresql
    # or use the bind from op.get_bind()

    # Using op.execute with the compiled statement
    # Note: statement.compile(op.get_bind()) might not work directly if op.get_bind() is not available at module level
    # but inside upgrade() it is.

    # We will do the compilation inside upgrade
    pass

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Keeping the auto-generated changes as they seem to be valid type fixes detected
    op.alter_column('usda_survey_record', 'begin_code',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='begin_code::integer')
    op.alter_column('usda_survey_record', 'end_code',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='end_code::integer')
    # ### end Alembic commands ###

    # Create data_portal schema
    op.execute("CREATE SCHEMA IF NOT EXISTS data_portal")

    # Helper to create MV
    def create_mv(name, stmt):
        compiled = stmt.compile(dialect=sa.dialects.postgresql.dialect(), compile_kwargs={"literal_binds": True})
        op.execute(f"CREATE MATERIALIZED VIEW data_portal.{name} AS {compiled}")
        # Add unique index for concurrent refresh if possible.
        # For now, we just create the view.
        # If we want concurrent refresh, we need a unique index.
        # Let's try to identify a unique key for each view if possible, or skip for now.

    create_mv("mv_biomass_search", mv_biomass_search)
    op.execute("CREATE UNIQUE INDEX idx_mv_biomass_search_id ON data_portal.mv_biomass_search (id)")

    create_mv("mv_biomass_composition", mv_biomass_composition)
    # Composition might not have a single unique ID easily without a synthetic key.
    # It groups by resource_id, analysis_type, parameter_name.
    op.execute("CREATE UNIQUE INDEX idx_mv_biomass_composition_key ON data_portal.mv_biomass_composition (resource_id, analysis_type, parameter_name)")

    create_mv("mv_biomass_county_production", mv_biomass_county_production)
    op.execute("CREATE UNIQUE INDEX idx_mv_biomass_county_production_id ON data_portal.mv_biomass_county_production (id)")

    create_mv("mv_biomass_availability", mv_biomass_availability)
    op.execute("CREATE UNIQUE INDEX idx_mv_biomass_availability_resource_id ON data_portal.mv_biomass_availability (resource_id)")

    create_mv("mv_biomass_sample_stats", mv_biomass_sample_stats)
    op.execute("CREATE UNIQUE INDEX idx_mv_biomass_sample_stats_resource_id ON data_portal.mv_biomass_sample_stats (resource_id)")

    create_mv("mv_biomass_fermentation", mv_biomass_fermentation)
    op.execute("CREATE UNIQUE INDEX idx_mv_biomass_fermentation_key ON data_portal.mv_biomass_fermentation (resource_id, strain_name, parameter_name)")

    create_mv("mv_biomass_gasification", mv_biomass_gasification)
    op.execute("CREATE UNIQUE INDEX idx_mv_biomass_gasification_key ON data_portal.mv_biomass_gasification (resource_id, parameter_name)")

    create_mv("mv_biomass_pricing", mv_biomass_pricing)
    op.execute("CREATE UNIQUE INDEX idx_mv_biomass_pricing_id ON data_portal.mv_biomass_pricing (id)")


def downgrade() -> None:
    """Downgrade schema."""

    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_pricing")
    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_gasification")
    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_fermentation")
    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_sample_stats")
    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_availability")
    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_county_production")
    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_composition")
    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_search")

    op.execute("DROP SCHEMA IF EXISTS data_portal")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usda_survey_record', 'end_code',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('usda_survey_record', 'begin_code',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
