"""update_mv_biomass_sample_stats

Revision ID: f5fe3dab0af2
Revises: f5ac1b135099
Create Date: 2026-03-08 23:15:35.084236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from ca_biositing.datamodels.data_portal_views import mv_biomass_sample_stats


# revision identifiers, used by Alembic.
revision: str = 'f5fe3dab0af2'
down_revision: Union[str, Sequence[str], None] = 'f5ac1b135099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_sample_stats")

    # Recreate with new definition
    compiled = mv_biomass_sample_stats.compile(dialect=sa.dialects.postgresql.dialect(), compile_kwargs={"literal_binds": True})
    op.execute(f"CREATE MATERIALIZED VIEW data_portal.mv_biomass_sample_stats AS {compiled}")
    op.execute("CREATE UNIQUE INDEX idx_mv_biomass_sample_stats_resource_id ON data_portal.mv_biomass_sample_stats (resource_id)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # We can't easily revert to the exact previous SQL without duplicating it here,
    # but for now we can just drop it. The previous migration created it.
    op.execute("DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_sample_stats")
    # ### end Alembic commands ###
