"""Add record_id to LandiqRecord and set as identifier

Revision ID: fa2a3ff24010
Revises: 20d0b6aa3316
Create Date: 2026-01-20 14:05:40.545990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2a3ff24010'
down_revision: Union[str, Sequence[str], None] = '20d0b6aa3316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landiq_record', sa.Column('record_id', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landiq_record', 'record_id')
    # ### end Alembic commands ###
