"""Finalize data portal view logic and sample stats

Revision ID: fabb4602bbe0
Revises: 9fe87687000a
Create Date: 2026-03-16 11:43:04.466216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fabb4602bbe0'
down_revision: Union[str, Sequence[str], None] = '9fe87687000a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
