"""adding full name slot to contact

Revision ID: fd64e8f83e51
Revises: 57aa2f5fbdaf
Create Date: 2026-02-05 19:19:47.872596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd64e8f83e51'
down_revision: Union[str, Sequence[str], None] = '57aa2f5fbdaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'name')
    # ### end Alembic commands ###
