--
-- Name: infrastructure_biosolids_facilities; Type: TABLE; Schema: -; Owner: -
--

CREATE TABLE IF NOT EXISTS infrastructure_biosolids_facilities (
    biosolid_facility_id SERIAL,
    report_submitted_date date,
    latitude numeric,
    longitude numeric,
    facility text,
    authority text,
    plant_type text,
    aqmd text,
    facility_address text,
    facility_city text,
    state text,
    facility_zip text,
    facility_county text,
    mailing_street_1 text,
    mailing_city text,
    mailing_state text,
    mailing_zip text,
    biosolids_number text,
    biosolids_contact text,
    biosolids_contact_phone text,
    biosolids_contact_email text,
    adwf numeric,
    potw_biosolids_generated integer,
    twtds_biosolids_treated integer,
    class_b_land_app integer,
    class_b_applier text,
    class_a_compost integer,
    class_a_heat_dried integer,
    class_a_other integer,
    class_a_other_applier text,
    twtds_transfer_to_second_preparer integer,
    twtds_second_preparer_name text,
    adc_or_final_c integer,
    landfill integer,
    landfill_name text,
    surface_disposal integer,
    deepwell_injection text,
    stored integer,
    longterm_treatment integer,
    other integer,
    name_of_other text,
    incineration integer,
    CONSTRAINT infrastructure_biosolids_facilities_pkey PRIMARY KEY (biosolid_facility_id)
);
