"""fixed biomass_test_id column

Revision ID: 426707fe05a6
Revises: f89ddeb113a7
Create Date: 2025-10-22 18:48:55.894859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '426707fe05a6'
down_revision: Union[str, Sequence[str], None] = 'f89ddeb113a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biomass_test', sa.Column('biomass_test_id', sa.Integer(), nullable=False))
    op.drop_column('biomass_test', 'biomass_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biomass_test', sa.Column('biomass_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('biomass_test', 'biomass_test_id')
    # ### end Alembic commands ###
