"""updated biomass ontology to note

Revision ID: 674b6c8724ae
Revises: 264f22d81114
Create Date: 2025-10-22 03:06:23.749451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '674b6c8724ae'
down_revision: Union[str, Sequence[str], None] = '264f22d81114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biomass', sa.Column('biomass_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('biomass', 'biomass_ontology')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biomass', sa.Column('biomass_ontology', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('biomass', 'biomass_notes')
    # ### end Alembic commands ###
