"""adding biomass_test table

Revision ID: f89ddeb113a7
Revises: 674b6c8724ae
Create Date: 2025-10-22 18:45:51.702743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f89ddeb113a7'
down_revision: Union[str, Sequence[str], None] = '674b6c8724ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biomass_test',
    sa.Column('biomass_id', sa.Integer(), nullable=False),
    sa.Column('biomass_test_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('biomass_test_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('biomass_id')
    )
    op.create_index(op.f('ix_biomass_test_biomass_test_name'), 'biomass_test', ['biomass_test_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_biomass_test_biomass_test_name'), table_name='biomass_test')
    op.drop_table('biomass_test')
    # ### end Alembic commands ###
