"""Add county to landiq_record

Revision ID: 17a44ed16381
Revises: 9809213445bb
Create Date: 2026-02-03 11:04:33.368062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a44ed16381'
down_revision: Union[str, Sequence[str], None] = '9809213445bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landiq_record', sa.Column('county', sa.Text(), nullable=True))
    #op.drop_index(op.f('unique_record_id'), table_name='landiq_record')
    #op.drop_index(op.f('unique_geom_dataset_md5'), table_name='polygon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_index(op.f('unique_geom_dataset_md5'), 'polygon', [sa.literal_column('md5(geom)'), 'dataset_id'], unique=True)
    #op.create_index(op.f('unique_record_id'), 'landiq_record', ['record_id'], unique=True)
    op.drop_column('landiq_record', 'county')
    # ### end Alembic commands ###
