"""trying with fixing the base

Revision ID: 2b18e6e5e72d
Revises: 1ace3fc9c593
Create Date: 2026-01-07 20:55:34.214689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b18e6e5e72d'
down_revision: Union[str, Sequence[str], None] = '1ace3fc9c593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
