"""Ensure record_id unique constraints are preserved in SQLAlchemy models

Revision ID: 52832cd53281
Revises: 33694e64f712
Create Date: 2026-01-18 14:56:08.368979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52832cd53281'
down_revision: Union[str, Sequence[str], None] = '33694e64f712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # We manually fix the foreign key to point to 'dataset' instead of 'data_source'
    # to avoid IntegrityError with existing data.
    op.drop_constraint('observation_dataset_id_fkey', 'observation', type_='foreignkey')
    op.create_foreign_key('observation_dataset_id_fkey', 'observation', 'dataset', ['dataset_id'], ['id'])

    # We comment out the drop_constraint calls for unique record_id because
    # we want to preserve them for upsert logic.
    # op.drop_constraint(op.f('uq_aim1_record_base_record_id'), 'aim1_record_base', type_='unique')
    # ... (other drops)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('observation_dataset_id_fkey', 'observation', type_='foreignkey')
    op.create_foreign_key('observation_dataset_id_fkey', 'observation', 'data_source', ['dataset_id'], ['id'])
    # ### end Alembic commands ###
