"""Fixed alembic gen_sqla so all inherit from same base

Revision ID: 62ef89b0050a
Revises: 2b41e390fc5d
Create Date: 2026-01-07 18:33:17.030868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ef89b0050a'
down_revision: Union[str, Sequence[str], None] = '2b41e390fc5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
