"""adding county to location_address and condensing name in contact

Revision ID: 7a1c996e0a6c
Revises: be8afc399f71
Create Date: 2026-01-30 13:27:26.784434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1c996e0a6c'
down_revision: Union[str, Sequence[str], None] = 'be8afc399f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('name', sa.Text(), nullable=True))
    op.drop_column('contact', 'first_name')
    op.drop_column('contact', 'last_name')
    #op.drop_index(op.f('unique_record_id'), table_name='landiq_record')
    op.add_column('location_address', sa.Column('county', sa.Text(), nullable=True))
    #op.drop_index(op.f('unique_geom_dataset_md5'), table_name='polygon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_index(op.f('unique_geom_dataset_md5'), 'polygon', [sa.literal_column('md5(geom)'), 'dataset_id'], unique=True)
    op.drop_column('location_address', 'county')
    #op.create_index(op.f('unique_record_id'), 'landiq_record', ['record_id'], unique=True)
    op.add_column('contact', sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('contact', sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('contact', 'name')
    # ### end Alembic commands ###
