"""adding pct to landiq record

Revision ID: 807417ade886
Revises: 823ec0ea8e4e
Create Date: 2026-01-21 10:26:40.464700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807417ade886'
down_revision: Union[str, Sequence[str], None] = '823ec0ea8e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landiq_record', sa.Column('pct1', sa.Float(), nullable=True))
    op.add_column('landiq_record', sa.Column('pct2', sa.Float(), nullable=True))
    op.add_column('landiq_record', sa.Column('pct3', sa.Float(), nullable=True))
    op.add_column('landiq_record', sa.Column('pct4', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landiq_record', 'pct4')
    op.drop_column('landiq_record', 'pct3')
    op.drop_column('landiq_record', 'pct2')
    op.drop_column('landiq_record', 'pct1')
    # ### end Alembic commands ###
