"""Fix Polygon identifier to use id instead of geom

Revision ID: 823ec0ea8e4e
Revises: cca37a7cb9ac
Create Date: 2026-01-20 18:30:53.026780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823ec0ea8e4e'
down_revision: Union[str, Sequence[str], None] = 'cca37a7cb9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.alter_column('infrastructure_combustion_plants', 'geom',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('infrastructure_district_energy_systems', 'geom',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('infrastructure_food_processing_facilities', 'geom',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('infrastructure_msw_to_energy_anaerobic_digesters', 'geom',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('landiq_record_polygon_id_fkey'), 'landiq_record', type_='foreignkey')
    op.execute("ALTER TABLE landiq_record ALTER COLUMN polygon_id TYPE INTEGER USING NULL")
    op.create_foreign_key(None, 'landiq_record', 'polygon', ['polygon_id'], ['id'])
    op.alter_column('polygon', 'geom',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('uq_polygon_geom'), 'polygon', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_polygon_geom'), 'polygon', ['geom'], postgresql_nulls_not_distinct=False)
    op.alter_column('polygon', 'geom',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'landiq_record', type_='foreignkey')
    op.create_foreign_key(op.f('landiq_record_polygon_id_fkey'), 'landiq_record', 'polygon', ['polygon_id'], ['geom'])
    op.alter_column('landiq_record', 'polygon_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('infrastructure_msw_to_energy_anaerobic_digesters', 'geom',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('infrastructure_food_processing_facilities', 'geom',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('infrastructure_district_energy_systems', 'geom',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('infrastructure_combustion_plants', 'geom',
               existing_type=sa.TEXT(),
               nullable=False)
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    # ### end Alembic commands ###
