"""refactor and update env.py

Revision ID: 9be24ffa7bb9
Revises: 15467b7f2f3d
Create Date: 2026-01-07 16:50:27.201523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9be24ffa7bb9'
down_revision: Union[str, Sequence[str], None] = '15467b7f2f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_subclass')
    op.drop_table('usda_market_report')
    op.drop_table('infrastructure_cafo_manure_locations')
    op.drop_table('experiment_equipment')
    op.drop_table('lookup_base')
    op.drop_table('infrastructure_ethanol_biorefineries')
    op.drop_table('etl_run')
    op.drop_table('polygon')
    op.drop_table('calorimetry_record')
    op.drop_table('base_entity')
    op.drop_table('method')
    op.drop_table('infrastructure_landfills')
    op.drop_table('observation')
    op.drop_table('equipment')
    op.drop_table('pretreatment_record')
    op.drop_table('infrastructure_biosolids_facilities')
    op.drop_table('prepared_sample')
    op.drop_table('infrastructure_district_energy_systems')
    op.drop_table('parameter_category')
    op.drop_table('xrd_record')
    op.drop_table('resource_class')
    op.drop_table('preparation_method')
    op.drop_table('strain')
    op.drop_table('infrastructure_food_processing_facilities')
    op.drop_table('file_object_metadata')
    op.drop_table('ftnir_record')
    op.drop_table('collection_method')
    op.drop_table('harvest_method')
    op.drop_table('physical_characteristic')
    op.drop_table('experiment')
    op.drop_table('parameter')
    op.drop_table('infrastructure_livestock_anaerobic_digesters')
    op.drop_table('experiment_analysis')
    op.drop_table('preparation_method_abbreviation')
    op.drop_table('usda_term_map')
    op.drop_table('xrf_record')
    op.drop_table('source_type')
    op.drop_table('lineage_group')
    op.drop_table('icp_record')
    op.drop_table('infrastructure_wastewater_treatment_plants')
    op.drop_table('usda_commodity')
    op.drop_table('infrastructure_combustion_plants')
    op.drop_table('aim1_record_base')
    op.drop_table('ultimate_record')
    op.drop_table('soil_type')
    op.drop_table('usda_survey_record')
    op.drop_table('facility_record')
    op.drop_table('autoclave_record')
    op.drop_table('usda_domain')
    op.drop_table('gasification_record')
    op.drop_table('infrastructure_msw_to_energy_anaerobic_digesters')
    op.drop_table('ag_treatment')
    op.drop_table('location_resolution')
    op.drop_table('analysis_type')
    op.drop_table('method_category')
    op.drop_table('resource_morphology')
    op.drop_table('rgb_record')
    op.drop_table('primary_ag_product')
    op.drop_table('dimension_type')
    op.drop_table('provider')
    op.drop_table('location_address')
    op.drop_table('parameter_category_parameter')
    op.drop_table('resource_availability')
    op.drop_table('billion_ton2023_record')
    op.drop_table('processing_method')
    op.drop_table('parameter_unit')
    op.drop_table('infrastructure_saf_and_renewable_diesel_plants')
    op.drop_table('usda_survey_program')
    op.drop_table('method_abbrev')
    op.drop_table('infrastructure_biodiesel_plants')
    op.drop_table('compositional_record')
    op.drop_table('resource_usda_commodity_map')
    op.drop_table('dataset')
    op.drop_table('field_sample')
    op.drop_table('field_sample_condition')
    op.drop_table('data_source')
    op.drop_table('landiq_record')
    op.drop_table('field_storage_method')
    op.drop_table('method_standard')
    op.drop_table('experiment_method')
    op.drop_table('usda_census_record')
    op.drop_table('location_soil_type')
    op.drop_table('experiment_prepared_sample')
    op.drop_table('fermentation_record')
    op.drop_table('entity_lineage')
    op.drop_table('data_source_type')
    op.drop_table('resource_counterfactual')
    op.drop_table('contact')
    op.drop_table('proximate_record')
    op.drop_table('usda_statistic_category')
    op.drop_table('unit')
    op.drop_table('aim2_record_base')
    op.drop_table('geography')
    op.drop_table('resource')
    op.drop_table('usda_market_record')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usda_market_record',
    sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('report_begin_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('report_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('report_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('commodity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('market_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grp', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('class_', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('variety', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('protein_pct', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('application', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pkg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sale_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('freight', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('trans_mode', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('market_type_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('market_category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usda_market_record_pkey'))
    )
    op.create_table('resource',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resource_class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_subclass_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('test', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_ag_product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('resource_pkey'))
    )
    op.create_table('geography',
    sa.Column('geoid', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('state_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state_fips', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('county_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('county_fips', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('region_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agg_level_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('geoid', name=op.f('geography_pkey'))
    )
    op.create_table('aim2_record_base',
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qc_pass', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calc_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calc_analyst_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('aim2_record_base_pkey'))
    )
    op.create_table('unit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('unit_pkey'))
    )
    op.create_table('usda_statistic_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usda_statistic_category_pkey'))
    )
    op.create_table('proximate_record',
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qc_pass', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analyst_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('proximate_record_pkey'))
    )
    op.create_table('contact',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('affiliation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('contact_pkey'))
    )
    op.create_table('resource_counterfactual',
    sa.Column('geoid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('counterfactual_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('animal_bedding_percent', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('animal_bedding_source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('animal_feed_percent', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('animal_feed_source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bioelectricty_percent', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bioelectricty_source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('burn_percent', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('burn_source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('compost_percent', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('compost_source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('landfill_percent', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('landfill_source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('counterfactual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('resource_counterfactual_pkey'))
    )
    op.create_table('data_source_type',
    sa.Column('source_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('data_source_type_pkey'))
    )
    op.create_table('entity_lineage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_table', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_row_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('entity_lineage_pkey'))
    )
    op.create_table('fermentation_record',
    sa.Column('strain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pretreatment_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('eh_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('replicate_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('well_position', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('agitation_rpm', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('vessel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analyte_detection_equipment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qc_pass', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calc_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calc_analyst_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fermentation_record_pkey'))
    )
    op.create_table('experiment_prepared_sample',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prepared_sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('experiment_prepared_sample_pkey'))
    )
    op.create_table('location_soil_type',
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('soil_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('location_soil_type_pkey'))
    )
    op.create_table('usda_census_record',
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('geoid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('commodity_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usda_census_record_pkey'))
    )
    op.create_table('experiment_method',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('experiment_method_pkey'))
    )
    op.create_table('method_standard',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('method_standard_pkey'))
    )
    op.create_table('field_storage_method',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('field_storage_method_pkey'))
    )
    op.create_table('landiq_record',
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('polygon_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('main_crop', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('secondary_crop', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tertiary_crop', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quaternary_crop', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('irrigated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('acres', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('landiq_record_pkey'))
    )
    op.create_table('data_source',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('publisher', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('license', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_source_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('full_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creator', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contributor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('biocirv', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('format', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('language', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('relation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('temporal_coverage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_coverage_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rights', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('data_source_pkey'))
    )
    op.create_table('field_sample_condition',
    sa.Column('field_sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ag_treatment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_application_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('treatment_amount_per_acre', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('processing_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('field_sample_condition_pkey'))
    )
    op.create_table('field_sample',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('collector_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_collection_source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount_collected', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('amount_collected_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sampling_location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('field_storage_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('field_storage_duration_value', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('field_storage_duration_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('field_storage_location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('collection_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('collection_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('harvest_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('harvest_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('field_sample_storage_location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('field_sample_pkey'))
    )
    op.create_table('dataset',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('record_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('dataset_pkey'))
    )
    op.create_table('resource_usda_commodity_map',
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usda_commodity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('match_tier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('primary_ag_product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('resource_usda_commodity_map_pkey'))
    )
    op.create_table('compositional_record',
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qc_pass', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analyst_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('compositional_record_pkey'))
    )
    op.create_table('infrastructure_biodiesel_plants',
    sa.Column('biodiesel_plant_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bbi_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('capacity_mmg_per_y', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedstock', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('coordinates', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('biodiesel_plant_id', name=op.f('infrastructure_biodiesel_plants_pkey'))
    )
    op.create_table('method_abbrev',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('method_abbrev_pkey'))
    )
    op.create_table('usda_survey_program',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usda_survey_program_pkey'))
    )
    op.create_table('infrastructure_saf_and_renewable_diesel_plants',
    sa.Column('ibcc_index', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('capacity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('feedstock', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('products', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('coordinates', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ibcc_index', name=op.f('infrastructure_saf_and_renewable_diesel_plants_pkey'))
    )
    op.create_table('parameter_unit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parameter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alternate_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('parameter_unit_pkey'))
    )
    op.create_table('processing_method',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('processing_method_pkey'))
    )
    op.create_table('billion_ton2023_record',
    sa.Column('subclass_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('geoid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('county_square_miles', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scenario_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price_offered_usd', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('production', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('production_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('btu_ton', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('production_energy_content', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('energy_content_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_density_dtpersqmi', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('land_source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('billion_ton2023_record_pkey'))
    )
    op.create_table('resource_availability',
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('geoid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('from_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year_round', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('resource_availability_pkey'))
    )
    op.create_table('parameter_category_parameter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parameter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parameter_category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('parameter_category_parameter_pkey'))
    )
    op.create_table('location_address',
    sa.Column('geography_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address_line1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address_line2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zip', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_anonymous', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('location_address_pkey'))
    )
    op.create_table('provider',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_pkey'))
    )
    op.create_table('dimension_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('dimension_type_pkey'))
    )
    op.create_table('primary_ag_product',
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('primary_ag_product_pkey'))
    )
    op.create_table('rgb_record',
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qc_pass', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analyst_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rgb_record_pkey'))
    )
    op.create_table('resource_morphology',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('morphology_uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('resource_morphology_pkey'))
    )
    op.create_table('method_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('method_category_pkey'))
    )
    op.create_table('analysis_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('analysis_type_pkey'))
    )
    op.create_table('location_resolution',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('location_resolution_pkey'))
    )
    op.create_table('ag_treatment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ag_treatment_pkey'))
    )
    op.create_table('infrastructure_msw_to_energy_anaerobic_digesters',
    sa.Column('wte_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('county', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('equivalent_generation', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('feedstock', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dayload', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('dayload_bdt', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('facility_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wkt_geom', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('geom', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('wte_id', name=op.f('infrastructure_msw_to_energy_anaerobic_digesters_pkey'))
    )
    op.create_table('gasification_record',
    sa.Column('feedstock_mass', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bed_temperature', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('gas_flow_rate', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qc_pass', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calc_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calc_analyst_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('gasification_record_pkey'))
    )
    op.create_table('usda_domain',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usda_domain_pkey'))
    )
    op.create_table('autoclave_record',
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qc_pass', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calc_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calc_analyst_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('autoclave_record_pkey'))
    )
    op.create_table('facility_record',
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('facility_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('capacity_mw', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('operator', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('facility_record_pkey'))
    )
    op.create_table('usda_survey_record',
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('geoid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('commodity_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('survey_program_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('survey_period', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reference_month', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seasonal_flag', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usda_survey_record_pkey'))
    )
    op.create_table('soil_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('soil_type_pkey'))
    )
    op.create_table('ultimate_record',
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qc_pass', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analyst_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ultimate_record_pkey'))
    )
    op.create_table('aim1_record_base',
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qc_pass', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analyst_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('aim1_record_base_pkey'))
    )
    op.create_table('infrastructure_combustion_plants',
    sa.Column('combustion_fid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('objectid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('county', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('equivalent_generation', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('np_mw', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('cf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('yearload', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fuel', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wkt_geom', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('geom', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('combustion_fid', name=op.f('infrastructure_combustion_plants_pkey'))
    )
    op.create_table('usda_commodity',
    sa.Column('usda_source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('usda_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parent_commodity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usda_commodity_pkey'))
    )
    op.create_table('infrastructure_wastewater_treatment_plants',
    sa.Column('plant_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('codigestion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('flow_design_adjusted', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('flow_average', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('biosolids', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('excess_flow', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('biogas_utilized', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('flaring', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('excess_mass_loading_rate', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('excess_mass_loading_rate_wet', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('methane_production', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('energy_content', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('electric_kw', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('thermal_mmbtu_d', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('electric_kwh', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('thermal_annual_mmbtu_y', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('anaerobic_digestion_facility', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('county', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dayload_bdt', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('dayload', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('equivalent_generation', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('facility_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('feedstock', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('zipcode', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('plant_id', name=op.f('infrastructure_wastewater_treatment_plants_pkey'))
    )
    op.create_table('icp_record',
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qc_pass', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analyst_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('icp_record_pkey'))
    )
    op.create_table('lineage_group',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('lineage_group_pkey'))
    )
    op.create_table('source_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('source_type_pkey'))
    )
    op.create_table('xrf_record',
    sa.Column('maybe_wavelength_nm', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('maybe_intensity', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('maybe_energy_slope', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('maybe_energy_offset', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qc_pass', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analyst_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('xrf_record_pkey'))
    )
    op.create_table('usda_term_map',
    sa.Column('source_system', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_term', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('usda_commodity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usda_term_map_pkey'))
    )
    op.create_table('preparation_method_abbreviation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('preparation_method_abbreviation_pkey'))
    )
    op.create_table('experiment_analysis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analysis_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('experiment_analysis_pkey'))
    )
    op.create_table('infrastructure_livestock_anaerobic_digesters',
    sa.Column('digester_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('digester_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('profile', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('year_operational', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('animal_type_class', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('animal_types', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pop_feeding_digester', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_pop_feeding_digester', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cattle', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dairy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('poultry', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('swine', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('codigestion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('biogas_generation_estimate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('electricity_generated', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('biogas_end_uses', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('methane_emission_reductions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('digester_id', name=op.f('infrastructure_livestock_anaerobic_digesters_pkey'))
    )
    op.create_table('parameter',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('standard_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calculated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('parameter_pkey'))
    )
    op.create_table('experiment',
    sa.Column('analyst_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exper_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('exper_duration', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('exper_duration_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exper_location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('experiment_pkey'))
    )
    op.create_table('physical_characteristic',
    sa.Column('field_sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('particle_length', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('particle_width', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('particle_height', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('particle_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('physical_characteristic_pkey'))
    )
    op.create_table('harvest_method',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('harvest_method_pkey'))
    )
    op.create_table('collection_method',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_method_pkey'))
    )
    op.create_table('ftnir_record',
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qc_pass', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analyst_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ftnir_record_pkey'))
    )
    op.create_table('file_object_metadata',
    sa.Column('data_source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bucket_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_format', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('checksum_md5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checksum_sha256', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('file_object_metadata_pkey'))
    )
    op.create_table('infrastructure_food_processing_facilities',
    sa.Column('processing_facility_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('county', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('company', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('join_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('master_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subtype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_fid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processing_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zip', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wkt_geom', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('geom', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('processing_facility_id', name=op.f('infrastructure_food_processing_facilities_pkey'))
    )
    op.create_table('strain',
    sa.Column('parent_strain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('strain_pkey'))
    )
    op.create_table('preparation_method',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prep_method_abbrev_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prep_temp_c', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('drying_step', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('preparation_method_pkey'))
    )
    op.create_table('resource_class',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('resource_class_pkey'))
    )
    op.create_table('xrd_record',
    sa.Column('maybe_scan_low_nm', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('maybe_scan_high_nm', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qc_pass', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analyst_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('xrd_record_pkey'))
    )
    op.create_table('parameter_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('parameter_category_pkey'))
    )
    op.create_table('infrastructure_district_energy_systems',
    sa.Column('des_fid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cbg_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('system', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_fuel', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('secondary_fuel', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('usetype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cap_st', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('cap_hw', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('cap_cw', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('chpcg_cap', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('excess_c', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('excess_h', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wkt_geom', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('geom', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('des_fid', name=op.f('infrastructure_district_energy_systems_pkey'))
    )
    op.create_table('prepared_sample',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('field_sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prep_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prep_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('preparer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('prepared_sample_pkey'))
    )
    op.create_table('infrastructure_biosolids_facilities',
    sa.Column('biosolid_facility_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_submitted_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('facility', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('authority', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('plant_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aqmd', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('facility_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('facility_city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('facility_zip', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('facility_county', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mailing_street_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mailing_city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mailing_state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mailing_zip', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('biosolids_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('biosolids_contact', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('biosolids_contact_phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('biosolids_contact_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('adwf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('potw_biosolids_generated', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('twtds_biosolids_treated', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_b_land_app', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_b_applier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('class_a_compost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_a_heat_dried', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_a_other', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_a_other_applier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('twtds_transfer_to_second_preparer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('twtds_second_preparer_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('adc_or_final_c', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('landfill', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('landfill_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('surface_disposal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deepwell_injection', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stored', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('longterm_treatment', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('other', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name_of_other', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('incineration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('biosolid_facility_id', name=op.f('infrastructure_biosolids_facilities_pkey'))
    )
    op.create_table('pretreatment_record',
    sa.Column('pretreatment_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('eh_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reaction_block_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('block_position', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('replicate_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qc_pass', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calc_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calc_analyst_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pretreatment_record_pkey'))
    )
    op.create_table('equipment',
    sa.Column('equipment_location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('equipment_pkey'))
    )
    op.create_table('observation',
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('record_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parameter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dimension_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dimension_value', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('dimension_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('observation_pkey'))
    )
    op.create_table('infrastructure_landfills',
    sa.Column('project_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('project_int_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ghgrp_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('landfill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('landfill_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('physical_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('county', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('ownership_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('landfill_owner_orgs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('landfill_opened_year', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('landfill_closure_year', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('landfill_status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('waste_in_place', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('waste_in_place_year', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('lfg_system_in_place', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('lfg_collected', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('lfg_flared', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('project_status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('project_shutdown_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('project_type_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lfg_energy_project_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rng_delivery_method', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actual_mw_generation', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('rated_mw_capacity', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('lfg_flow_to_project', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('direct_emission_reductions', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('avoided_emission_reductions', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('project_id', name=op.f('infrastructure_landfills_pkey'))
    )
    op.create_table('method',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('method_abbrev_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method_category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method_standard_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detection_limits', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('method_pkey'))
    )
    op.create_table('base_entity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('base_entity_pkey'))
    )
    op.create_table('calorimetry_record',
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('technical_replicate_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qc_pass', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analyst_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('calorimetry_record_pkey'))
    )
    op.create_table('polygon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('geoid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('geom', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('polygon_pkey'))
    )
    op.create_table('etl_run',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pipeline_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('records_ingested', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('etl_run_pkey'))
    )
    op.create_table('infrastructure_ethanol_biorefineries',
    sa.Column('ethanol_biorefinery_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('capacity_mgy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('production_mgy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('constr_exp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ethanol_biorefinery_id', name=op.f('infrastructure_ethanol_biorefineries_pkey'))
    )
    op.create_table('lookup_base',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('lookup_base_pkey'))
    )
    op.create_table('experiment_equipment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('experiment_equipment_pkey'))
    )
    op.create_table('infrastructure_cafo_manure_locations',
    sa.Column('cafo_manure_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('owner_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('facility_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('town', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zip', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('animal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('animal_feed_operation_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('animal_units', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('animal_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manure_total_solids', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_accessed', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cafo_manure_id', name=op.f('infrastructure_cafo_manure_locations_pkey'))
    )
    op.create_table('usda_market_report',
    sa.Column('slug_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('slug_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('report_series_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('office_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('office_city_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('office_state_fips', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etl_run_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usda_market_report_pkey'))
    )
    op.create_table('resource_subclass',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('resource_subclass_pkey'))
    )
    # ### end Alembic commands ###
