"""Fixed alembic environment to import generated schemas

Revision ID: a8a3ea954e88
Revises: 9be24ffa7bb9
Create Date: 2026-01-07 17:03:49.308268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a3ea954e88'
down_revision: Union[str, Sequence[str], None] = '9be24ffa7bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
