"""removing test from resource

Revision ID: bb539f91106c
Revises: 293bb0c6918a
Create Date: 2026-01-16 16:58:27.464193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb539f91106c'
down_revision: Union[str, Sequence[str], None] = '293bb0c6918a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('test', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
