"""Remove hallucinations\

Revision ID: bfa07351a507
Revises: d82910ff757e
Create Date: 2025-12-17 00:05:46.750313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa07351a507'
down_revision: Union[str, Sequence[str], None] = '1e9784d75e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aim1_record_base', sa.Column('analyst_id', sa.Integer(), nullable=True))
    op.add_column('aim2_record_base', sa.Column('calc_method_id', sa.Integer(), nullable=True))
    op.add_column('aim2_record_base', sa.Column('calc_analyst_id', sa.Integer(), nullable=True))
    op.drop_column('aim2_record_base', 'analyst_id')
    op.add_column('autoclave_record', sa.Column('calc_method_id', sa.Integer(), nullable=True))
    op.add_column('autoclave_record', sa.Column('calc_analyst_id', sa.Integer(), nullable=True))
    op.drop_column('autoclave_record', 'analyst_id')
    op.add_column('calorimetry_record', sa.Column('analyst_id', sa.Integer(), nullable=True))
    op.add_column('compositional_record', sa.Column('analyst_id', sa.Integer(), nullable=True))
    op.add_column('contact', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('contact', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('contact', sa.Column('etl_run_id', sa.Text(), nullable=True))
    op.add_column('contact', sa.Column('lineage_group_id', sa.Integer(), nullable=True))
    op.add_column('data_source', sa.Column('data_source_type_id', sa.Integer(), nullable=True))
    op.add_column('data_source', sa.Column('full_title', sa.Text(), nullable=True))
    op.add_column('data_source', sa.Column('creator', sa.Text(), nullable=True))
    op.add_column('data_source', sa.Column('subject', sa.Text(), nullable=True))
    op.add_column('data_source', sa.Column('contributor', sa.Text(), nullable=True))
    op.add_column('data_source', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('data_source', sa.Column('type', sa.Text(), nullable=True))
    op.add_column('data_source', sa.Column('biocirv', sa.Boolean(), nullable=True))
    op.add_column('data_source', sa.Column('format', sa.Text(), nullable=True))
    op.add_column('data_source', sa.Column('language', sa.Text(), nullable=True))
    op.add_column('data_source', sa.Column('relation', sa.Text(), nullable=True))
    op.add_column('data_source', sa.Column('temporal_coverage', sa.Text(), nullable=True))
    op.add_column('data_source', sa.Column('location_coverage_id', sa.Integer(), nullable=True))
    op.add_column('data_source', sa.Column('rights', sa.Text(), nullable=True))
    op.drop_column('data_source', 'publication_date')
    op.drop_column('data_source', 'version')
    op.drop_column('data_source', 'author')
    op.add_column('fermentation_record', sa.Column('calc_method_id', sa.Integer(), nullable=True))
    op.add_column('fermentation_record', sa.Column('calc_analyst_id', sa.Integer(), nullable=True))
    op.drop_column('fermentation_record', 'analyst_id')
    op.add_column('ftnir_record', sa.Column('analyst_id', sa.Integer(), nullable=True))
    op.add_column('gasification_record', sa.Column('calc_method_id', sa.Integer(), nullable=True))
    op.add_column('gasification_record', sa.Column('calc_analyst_id', sa.Integer(), nullable=True))
    op.drop_column('gasification_record', 'analyst_id')
    op.add_column('icp_record', sa.Column('analyst_id', sa.Integer(), nullable=True))
    op.add_column('pretreatment_record', sa.Column('calc_method_id', sa.Integer(), nullable=True))
    op.add_column('pretreatment_record', sa.Column('calc_analyst_id', sa.Integer(), nullable=True))
    op.drop_column('pretreatment_record', 'analyst_id')
    op.add_column('provider', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('provider', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('provider', sa.Column('etl_run_id', sa.Text(), nullable=True))
    op.add_column('provider', sa.Column('lineage_group_id', sa.Integer(), nullable=True))
    op.add_column('proximate_record', sa.Column('analyst_id', sa.Integer(), nullable=True))
    op.add_column('rgb_record', sa.Column('analyst_id', sa.Integer(), nullable=True))
    op.add_column('ultimate_record', sa.Column('analyst_id', sa.Integer(), nullable=True))
    op.add_column('usda_market_record', sa.Column('market_type_category', sa.Text(), nullable=True))
    op.add_column('usda_market_record', sa.Column('market_category_id', sa.Integer(), nullable=True))
    op.drop_column('usda_market_record', 'market_type_catagory')
    op.drop_column('usda_market_record', 'market_catagory_id')
    op.add_column('xrd_record', sa.Column('analyst_id', sa.Integer(), nullable=True))
    op.add_column('xrf_record', sa.Column('analyst_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xrf_record', 'analyst_id')
    op.drop_column('xrd_record', 'analyst_id')
    op.add_column('usda_market_record', sa.Column('market_catagory_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('usda_market_record', sa.Column('market_type_catagory', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('usda_market_record', 'market_category_id')
    op.drop_column('usda_market_record', 'market_type_category')
    op.drop_column('ultimate_record', 'analyst_id')
    op.drop_column('rgb_record', 'analyst_id')
    op.drop_column('proximate_record', 'analyst_id')
    op.drop_column('provider', 'lineage_group_id')
    op.drop_column('provider', 'etl_run_id')
    op.drop_column('provider', 'updated_at')
    op.drop_column('provider', 'created_at')
    op.add_column('pretreatment_record', sa.Column('analyst_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pretreatment_record', 'calc_analyst_id')
    op.drop_column('pretreatment_record', 'calc_method_id')
    op.drop_column('icp_record', 'analyst_id')
    op.add_column('gasification_record', sa.Column('analyst_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('gasification_record', 'calc_analyst_id')
    op.drop_column('gasification_record', 'calc_method_id')
    op.drop_column('ftnir_record', 'analyst_id')
    op.add_column('fermentation_record', sa.Column('analyst_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('fermentation_record', 'calc_analyst_id')
    op.drop_column('fermentation_record', 'calc_method_id')
    op.add_column('data_source', sa.Column('author', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('data_source', sa.Column('version', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('data_source', sa.Column('publication_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('data_source', 'rights')
    op.drop_column('data_source', 'location_coverage_id')
    op.drop_column('data_source', 'temporal_coverage')
    op.drop_column('data_source', 'relation')
    op.drop_column('data_source', 'language')
    op.drop_column('data_source', 'format')
    op.drop_column('data_source', 'biocirv')
    op.drop_column('data_source', 'type')
    op.drop_column('data_source', 'date')
    op.drop_column('data_source', 'contributor')
    op.drop_column('data_source', 'subject')
    op.drop_column('data_source', 'creator')
    op.drop_column('data_source', 'full_title')
    op.drop_column('data_source', 'data_source_type_id')
    op.drop_column('contact', 'lineage_group_id')
    op.drop_column('contact', 'etl_run_id')
    op.drop_column('contact', 'updated_at')
    op.drop_column('contact', 'created_at')
    op.drop_column('compositional_record', 'analyst_id')
    op.drop_column('calorimetry_record', 'analyst_id')
    op.add_column('autoclave_record', sa.Column('analyst_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('autoclave_record', 'calc_analyst_id')
    op.drop_column('autoclave_record', 'calc_method_id')
    op.add_column('aim2_record_base', sa.Column('analyst_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('aim2_record_base', 'calc_analyst_id')
    op.drop_column('aim2_record_base', 'calc_method_id')
    op.drop_column('aim1_record_base', 'analyst_id')
    # ### end Alembic commands ###
