"""changing primary crop to primary_ag_product

Revision ID: e84690898528
Revises: fc422d3d9ea6
Create Date: 2025-12-23 16:04:40.644736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e84690898528'
down_revision: Union[str, Sequence[str], None] = 'fc422d3d9ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('primary_ag_product',
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('primary_crop')
    op.add_column('resource', sa.Column('primary_ag_product_id', sa.Integer(), nullable=True))
    op.drop_column('resource', 'primary_crop_id')
    op.add_column('resource_usda_commodity_map', sa.Column('primary_ag_product_id', sa.Integer(), nullable=True))
    op.drop_column('resource_usda_commodity_map', 'primary_crop_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_usda_commodity_map', sa.Column('primary_crop_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('resource_usda_commodity_map', 'primary_ag_product_id')
    op.add_column('resource', sa.Column('primary_crop_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('resource', 'primary_ag_product_id')
    op.create_table('primary_crop',
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('primary_crop_pkey'))
    )
    op.drop_table('primary_ag_product')
    # ### end Alembic commands ###
