"""adding infrastructure I think

Revision ID: fc422d3d9ea6
Revises: 5a6668dac367
Create Date: 2025-12-22 21:13:56.161244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc422d3d9ea6'
down_revision: Union[str, Sequence[str], None] = '5a6668dac367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_record',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('facility_name', sa.Text(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('capacity_mw', sa.Numeric(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('operator', sa.Text(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Text(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infrastructure_biodiesel_plants',
    sa.Column('biodiesel_plant_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('bbi_index', sa.Integer(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('capacity_mmg_per_y', sa.Integer(), nullable=True),
    sa.Column('feedstock', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('coordinates', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('biodiesel_plant_id')
    )
    op.create_table('infrastructure_biosolids_facilities',
    sa.Column('biosolid_facility_id', sa.Integer(), nullable=False),
    sa.Column('report_submitted_date', sa.Date(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('facility', sa.Text(), nullable=True),
    sa.Column('authority', sa.Text(), nullable=True),
    sa.Column('plant_type', sa.Text(), nullable=True),
    sa.Column('aqmd', sa.Text(), nullable=True),
    sa.Column('facility_address', sa.Text(), nullable=True),
    sa.Column('facility_city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('facility_zip', sa.Text(), nullable=True),
    sa.Column('facility_county', sa.Text(), nullable=True),
    sa.Column('mailing_street_1', sa.Text(), nullable=True),
    sa.Column('mailing_city', sa.Text(), nullable=True),
    sa.Column('mailing_state', sa.Text(), nullable=True),
    sa.Column('mailing_zip', sa.Text(), nullable=True),
    sa.Column('biosolids_number', sa.Text(), nullable=True),
    sa.Column('biosolids_contact', sa.Text(), nullable=True),
    sa.Column('biosolids_contact_phone', sa.Text(), nullable=True),
    sa.Column('biosolids_contact_email', sa.Text(), nullable=True),
    sa.Column('adwf', sa.Numeric(), nullable=True),
    sa.Column('potw_biosolids_generated', sa.Integer(), nullable=True),
    sa.Column('twtds_biosolids_treated', sa.Integer(), nullable=True),
    sa.Column('class_b_land_app', sa.Integer(), nullable=True),
    sa.Column('class_b_applier', sa.Text(), nullable=True),
    sa.Column('class_a_compost', sa.Integer(), nullable=True),
    sa.Column('class_a_heat_dried', sa.Integer(), nullable=True),
    sa.Column('class_a_other', sa.Integer(), nullable=True),
    sa.Column('class_a_other_applier', sa.Text(), nullable=True),
    sa.Column('twtds_transfer_to_second_preparer', sa.Integer(), nullable=True),
    sa.Column('twtds_second_preparer_name', sa.Text(), nullable=True),
    sa.Column('adc_or_final_c', sa.Integer(), nullable=True),
    sa.Column('landfill', sa.Integer(), nullable=True),
    sa.Column('landfill_name', sa.Text(), nullable=True),
    sa.Column('surface_disposal', sa.Integer(), nullable=True),
    sa.Column('deepwell_injection', sa.Text(), nullable=True),
    sa.Column('stored', sa.Integer(), nullable=True),
    sa.Column('longterm_treatment', sa.Integer(), nullable=True),
    sa.Column('other', sa.Integer(), nullable=True),
    sa.Column('name_of_other', sa.Text(), nullable=True),
    sa.Column('incineration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('biosolid_facility_id')
    )
    op.create_table('infrastructure_cafo_manure_locations',
    sa.Column('cafo_manure_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('owner_name', sa.Text(), nullable=True),
    sa.Column('facility_name', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('town', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('zip', sa.Text(), nullable=True),
    sa.Column('animal', sa.Text(), nullable=True),
    sa.Column('animal_feed_operation_type', sa.Text(), nullable=True),
    sa.Column('animal_units', sa.Integer(), nullable=True),
    sa.Column('animal_count', sa.Integer(), nullable=True),
    sa.Column('manure_total_solids', sa.Numeric(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('date_accessed', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('cafo_manure_id')
    )
    op.create_table('infrastructure_combustion_plants',
    sa.Column('combustion_fid', sa.Integer(), nullable=False),
    sa.Column('objectid', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('equivalent_generation', sa.Numeric(), nullable=True),
    sa.Column('np_mw', sa.Numeric(), nullable=True),
    sa.Column('cf', sa.Numeric(), nullable=True),
    sa.Column('yearload', sa.Integer(), nullable=True),
    sa.Column('fuel', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('wkt_geom', sa.Text(), nullable=True),
    sa.Column('geom', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('combustion_fid')
    )
    op.create_table('infrastructure_district_energy_systems',
    sa.Column('des_fid', sa.Integer(), nullable=False),
    sa.Column('cbg_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('system', sa.Text(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('primary_fuel', sa.Text(), nullable=True),
    sa.Column('secondary_fuel', sa.Text(), nullable=True),
    sa.Column('usetype', sa.Text(), nullable=True),
    sa.Column('cap_st', sa.Numeric(), nullable=True),
    sa.Column('cap_hw', sa.Numeric(), nullable=True),
    sa.Column('cap_cw', sa.Numeric(), nullable=True),
    sa.Column('chpcg_cap', sa.Numeric(), nullable=True),
    sa.Column('excess_c', sa.Numeric(), nullable=True),
    sa.Column('excess_h', sa.Numeric(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('wkt_geom', sa.Text(), nullable=True),
    sa.Column('geom', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('des_fid')
    )
    op.create_table('infrastructure_ethanol_biorefineries',
    sa.Column('ethanol_biorefinery_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('capacity_mgy', sa.Integer(), nullable=True),
    sa.Column('production_mgy', sa.Integer(), nullable=True),
    sa.Column('constr_exp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ethanol_biorefinery_id')
    )
    op.create_table('infrastructure_food_processing_facilities',
    sa.Column('processing_facility_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('join_count', sa.Integer(), nullable=True),
    sa.Column('master_type', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('subtype', sa.Text(), nullable=True),
    sa.Column('target_fid', sa.Integer(), nullable=True),
    sa.Column('processing_type', sa.Text(), nullable=True),
    sa.Column('zip', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('wkt_geom', sa.Text(), nullable=True),
    sa.Column('geom', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('processing_facility_id')
    )
    op.create_table('infrastructure_landfills',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('project_int_id', sa.Integer(), nullable=True),
    sa.Column('ghgrp_id', sa.Text(), nullable=True),
    sa.Column('landfill_id', sa.Integer(), nullable=True),
    sa.Column('landfill_name', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('physical_address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('zip_code', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('ownership_type', sa.Text(), nullable=True),
    sa.Column('landfill_owner_orgs', sa.Text(), nullable=True),
    sa.Column('landfill_opened_year', sa.Date(), nullable=True),
    sa.Column('landfill_closure_year', sa.Date(), nullable=True),
    sa.Column('landfill_status', sa.Text(), nullable=True),
    sa.Column('waste_in_place', sa.Integer(), nullable=True),
    sa.Column('waste_in_place_year', sa.Date(), nullable=True),
    sa.Column('lfg_system_in_place', sa.Boolean(), nullable=True),
    sa.Column('lfg_collected', sa.Numeric(), nullable=True),
    sa.Column('lfg_flared', sa.Numeric(), nullable=True),
    sa.Column('project_status', sa.Text(), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('project_start_date', sa.Date(), nullable=True),
    sa.Column('project_shutdown_date', sa.Date(), nullable=True),
    sa.Column('project_type_category', sa.Text(), nullable=True),
    sa.Column('lfg_energy_project_type', sa.Text(), nullable=True),
    sa.Column('rng_delivery_method', sa.Text(), nullable=True),
    sa.Column('actual_mw_generation', sa.Numeric(), nullable=True),
    sa.Column('rated_mw_capacity', sa.Numeric(), nullable=True),
    sa.Column('lfg_flow_to_project', sa.Numeric(), nullable=True),
    sa.Column('direct_emission_reductions', sa.Numeric(), nullable=True),
    sa.Column('avoided_emission_reductions', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('infrastructure_livestock_anaerobic_digesters',
    sa.Column('digester_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('project_type', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('digester_type', sa.Text(), nullable=True),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.Column('year_operational', sa.Date(), nullable=True),
    sa.Column('animal_type_class', sa.Text(), nullable=True),
    sa.Column('animal_types', sa.Text(), nullable=True),
    sa.Column('pop_feeding_digester', sa.Text(), nullable=True),
    sa.Column('total_pop_feeding_digester', sa.Integer(), nullable=True),
    sa.Column('cattle', sa.Integer(), nullable=True),
    sa.Column('dairy', sa.Integer(), nullable=True),
    sa.Column('poultry', sa.Integer(), nullable=True),
    sa.Column('swine', sa.Integer(), nullable=True),
    sa.Column('codigestion', sa.Text(), nullable=True),
    sa.Column('biogas_generation_estimate', sa.Integer(), nullable=True),
    sa.Column('electricity_generated', sa.Integer(), nullable=True),
    sa.Column('biogas_end_uses', sa.Text(), nullable=True),
    sa.Column('methane_emission_reductions', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('digester_id')
    )
    op.create_table('infrastructure_msw_to_energy_anaerobic_digesters',
    sa.Column('wte_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('equivalent_generation', sa.Numeric(), nullable=True),
    sa.Column('feedstock', sa.Text(), nullable=True),
    sa.Column('dayload', sa.Numeric(), nullable=True),
    sa.Column('dayload_bdt', sa.Numeric(), nullable=True),
    sa.Column('facility_type', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('wkt_geom', sa.Text(), nullable=True),
    sa.Column('geom', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('wte_id')
    )
    op.create_table('infrastructure_saf_and_renewable_diesel_plants',
    sa.Column('ibcc_index', sa.Integer(), nullable=False),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Text(), nullable=True),
    sa.Column('feedstock', sa.Text(), nullable=True),
    sa.Column('products', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('coordinates', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('ibcc_index')
    )
    op.create_table('infrastructure_wastewater_treatment_plants',
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('codigestion', sa.Text(), nullable=True),
    sa.Column('flow_design_adjusted', sa.Numeric(), nullable=True),
    sa.Column('flow_average', sa.Numeric(), nullable=True),
    sa.Column('biosolids', sa.Numeric(), nullable=True),
    sa.Column('excess_flow', sa.Numeric(), nullable=True),
    sa.Column('biogas_utilized', sa.Boolean(), nullable=True),
    sa.Column('flaring', sa.Boolean(), nullable=True),
    sa.Column('excess_mass_loading_rate', sa.Numeric(), nullable=True),
    sa.Column('excess_mass_loading_rate_wet', sa.Numeric(), nullable=True),
    sa.Column('methane_production', sa.Numeric(), nullable=True),
    sa.Column('energy_content', sa.Numeric(), nullable=True),
    sa.Column('electric_kw', sa.Numeric(), nullable=True),
    sa.Column('thermal_mmbtu_d', sa.Numeric(), nullable=True),
    sa.Column('electric_kwh', sa.Numeric(), nullable=True),
    sa.Column('thermal_annual_mmbtu_y', sa.Numeric(), nullable=True),
    sa.Column('anaerobic_digestion_facility', sa.Text(), nullable=True),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('dayload_bdt', sa.Numeric(), nullable=True),
    sa.Column('dayload', sa.Numeric(), nullable=True),
    sa.Column('equivalent_generation', sa.Numeric(), nullable=True),
    sa.Column('facility_type', sa.Text(), nullable=True),
    sa.Column('feedstock', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('zipcode', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('plant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('infrastructure_wastewater_treatment_plants')
    op.drop_table('infrastructure_saf_and_renewable_diesel_plants')
    op.drop_table('infrastructure_msw_to_energy_anaerobic_digesters')
    op.drop_table('infrastructure_livestock_anaerobic_digesters')
    op.drop_table('infrastructure_landfills')
    op.drop_table('infrastructure_food_processing_facilities')
    op.drop_table('infrastructure_ethanol_biorefineries')
    op.drop_table('infrastructure_district_energy_systems')
    op.drop_table('infrastructure_combustion_plants')
    op.drop_table('infrastructure_cafo_manure_locations')
    op.drop_table('infrastructure_biosolids_facilities')
    op.drop_table('infrastructure_biodiesel_plants')
    op.drop_table('facility_record')
    # ### end Alembic commands ###
