-- Compiled materialized view definitions
-- Generated from Python view modules after QC filtering changes
-- QC Filter: qc_pass != 'fail' (exclude only records marked as failed)
-- Date: 2026-04-07

-- View: mv_biomass_composition
SELECT row_number() OVER (ORDER BY anon_1.resource_id, anon_1.geoid, anon_1.analysis_type, anon_1.parameter_name, anon_1.unit) AS id, anon_1.resource_id, resource.name AS resource_name, anon_1.analysis_type, anon_1.parameter_name, anon_1.geoid, anon_1.unit, avg(anon_1.value) AS avg_value, min(anon_1.value) AS min_value, max(anon_1.value) AS max_value, stddev(anon_1.value) AS std_dev, count(*) AS observation_count
FROM (SELECT compositional_record.resource_id AS resource_id, 'compositional' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM compositional_record JOIN observation ON observation.record_id = compositional_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON compositional_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE compositional_record.qc_pass != 'fail' UNION ALL SELECT proximate_record.resource_id AS resource_id, 'proximate' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM proximate_record JOIN observation ON observation.record_id = proximate_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON proximate_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE proximate_record.qc_pass != 'fail' UNION ALL SELECT ultimate_record.resource_id AS resource_id, 'ultimate' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM ultimate_record JOIN observation ON observation.record_id = ultimate_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON ultimate_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE ultimate_record.qc_pass != 'fail' UNION ALL SELECT xrf_record.resource_id AS resource_id, 'xrf' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM xrf_record JOIN observation ON observation.record_id = xrf_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON xrf_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE xrf_record.qc_pass != 'fail' UNION ALL SELECT icp_record.resource_id AS resource_id, 'icp' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM icp_record JOIN observation ON observation.record_id = icp_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON icp_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE icp_record.qc_pass != 'fail' UNION ALL SELECT calorimetry_record.resource_id AS resource_id, 'calorimetry' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM calorimetry_record JOIN observation ON observation.record_id = calorimetry_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON calorimetry_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE calorimetry_record.qc_pass != 'fail' UNION ALL SELECT xrd_record.resource_id AS resource_id, 'xrd' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM xrd_record JOIN observation ON observation.record_id = xrd_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON xrd_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE xrd_record.qc_pass != 'fail' UNION ALL SELECT ftnir_record.resource_id AS resource_id, 'ftnir' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM ftnir_record JOIN observation ON observation.record_id = ftnir_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON ftnir_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE ftnir_record.qc_pass != 'fail' UNION ALL SELECT pretreatment_record.resource_id AS resource_id, 'pretreatment' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM pretreatment_record JOIN observation ON observation.record_id = pretreatment_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON pretreatment_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE pretreatment_record.qc_pass != 'fail') AS anon_1 JOIN resource ON anon_1.resource_id = resource.id GROUP BY anon_1.resource_id, resource.name, anon_1.analysis_type, anon_1.parameter_name, anon_1.geoid, anon_1.unit;

-- View: mv_biomass_gasification
SELECT row_number() OVER (ORDER BY gasification_record.resource_id, location_address.geography_id, decon_vessel.name, parameter.name, unit.name) AS id, gasification_record.resource_id, resource.name AS resource_name, decon_vessel.name AS reactor_type, parameter.name AS parameter_name, location_address.geography_id AS geoid, avg(observation.value) AS avg_value, min(observation.value) AS min_value, max(observation.value) AS max_value, stddev(observation.value) AS std_dev, count(*) AS observation_count, unit.name AS unit
FROM gasification_record JOIN resource ON gasification_record.resource_id = resource.id LEFT OUTER JOIN prepared_sample ON gasification_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id LEFT OUTER JOIN decon_vessel ON gasification_record.reactor_type_id = decon_vessel.id JOIN observation ON lower(observation.record_id) = lower(gasification_record.record_id) JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id
WHERE gasification_record.qc_pass != 'fail' GROUP BY gasification_record.resource_id, resource.name, location_address.geography_id, decon_vessel.name, parameter.name, unit.name;

-- View: mv_biomass_fermentation
SELECT row_number() OVER (ORDER BY fermentation_record.resource_id, strain.name, pm.name, em.name, parameter.name, unit.name) AS id, fermentation_record.resource_id, resource.name AS resource_name, strain.name AS strain_name, pm.name AS pretreatment_method, em.name AS enzyme_name, parameter.name AS product_name, avg(observation.value) AS avg_value, min(observation.value) AS min_value, max(observation.value) AS max_value, stddev(observation.value) AS std_dev, count(*) AS observation_count, unit.name AS unit
FROM fermentation_record JOIN resource ON fermentation_record.resource_id = resource.id LEFT OUTER JOIN strain ON fermentation_record.strain_id = strain.id LEFT OUTER JOIN method AS pm ON fermentation_record.pretreatment_method_id = pm.id LEFT OUTER JOIN method AS em ON fermentation_record.eh_method_id = em.id JOIN observation ON lower(observation.record_id) = lower(fermentation_record.record_id) JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id
WHERE fermentation_record.qc_pass != 'fail' GROUP BY fermentation_record.resource_id, resource.name, strain.name, pm.name, em.name, parameter.name, unit.name;

-- View: mv_biomass_sample_stats
SELECT resource.id AS resource_id, resource.name AS resource_name, count(distinct(anon_1.prepared_sample_id)) AS sample_count, count(distinct(provider.id)) AS supplier_count, count(distinct(anon_1.dataset_id)) AS dataset_count, count(*) AS total_record_count
FROM resource LEFT OUTER JOIN (SELECT compositional_record.resource_id AS resource_id, compositional_record.prepared_sample_id AS prepared_sample_id, compositional_record.dataset_id AS dataset_id
FROM compositional_record
WHERE compositional_record.qc_pass != 'fail' UNION ALL SELECT proximate_record.resource_id AS resource_id, proximate_record.prepared_sample_id AS prepared_sample_id, proximate_record.dataset_id AS dataset_id
FROM proximate_record
WHERE proximate_record.qc_pass != 'fail' UNION ALL SELECT ultimate_record.resource_id AS resource_id, ultimate_record.prepared_sample_id AS prepared_sample_id, ultimate_record.dataset_id AS dataset_id
FROM ultimate_record
WHERE ultimate_record.qc_pass != 'fail' UNION ALL SELECT xrf_record.resource_id AS resource_id, xrf_record.prepared_sample_id AS prepared_sample_id, xrf_record.dataset_id AS dataset_id
FROM xrf_record
WHERE xrf_record.qc_pass != 'fail' UNION ALL SELECT icp_record.resource_id AS resource_id, icp_record.prepared_sample_id AS prepared_sample_id, icp_record.dataset_id AS dataset_id
FROM icp_record
WHERE icp_record.qc_pass != 'fail' UNION ALL SELECT calorimetry_record.resource_id AS resource_id, calorimetry_record.prepared_sample_id AS prepared_sample_id, calorimetry_record.dataset_id AS dataset_id
FROM calorimetry_record
WHERE calorimetry_record.qc_pass != 'fail' UNION ALL SELECT xrd_record.resource_id AS resource_id, xrd_record.prepared_sample_id AS prepared_sample_id, xrd_record.dataset_id AS dataset_id
FROM xrd_record
WHERE xrd_record.qc_pass != 'fail' UNION ALL SELECT ftnir_record.resource_id AS resource_id, ftnir_record.prepared_sample_id AS prepared_sample_id, ftnir_record.dataset_id AS dataset_id
FROM ftnir_record
WHERE ftnir_record.qc_pass != 'fail' UNION ALL SELECT fermentation_record.resource_id AS resource_id, fermentation_record.prepared_sample_id AS prepared_sample_id, fermentation_record.dataset_id AS dataset_id
FROM fermentation_record
WHERE fermentation_record.qc_pass != 'fail' UNION ALL SELECT gasification_record.resource_id AS resource_id, gasification_record.prepared_sample_id AS prepared_sample_id, gasification_record.dataset_id AS dataset_id
FROM gasification_record
WHERE gasification_record.qc_pass != 'fail' UNION ALL SELECT pretreatment_record.resource_id AS resource_id, pretreatment_record.prepared_sample_id AS prepared_sample_id, pretreatment_record.dataset_id AS dataset_id
FROM pretreatment_record
WHERE pretreatment_record.qc_pass != 'fail') AS anon_1 ON anon_1.resource_id = resource.id LEFT OUTER JOIN prepared_sample ON CAST(anon_1.prepared_sample_id AS INTEGER) = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN provider ON field_sample.provider_id = provider.id GROUP BY resource.id, resource.name;
